import { formatNum as F } from '../../server/src/growth';
import type { Strings } from './ko';

/** English. 모양은 ko.ts(Strings)와 같다 */
export const en: Strings = {
  connecting: 'Connecting to the server…',
  loading: 'Loading…',
  gold: 'Gold',
  soul: 'Soulstones',
  icons: { shop: 'Shop', rank: 'Rank', rankN: (n: number) => `#${n}`, log: 'Log' },
  upMany: { ten: '×10', max: (n: number) => `Max +${n}` },
  quest: {
    title: 'Quests', next: 'Next', go: 'Go', claim: 'Claim', done: 'Done', after: 'After that', all: 'All done',
    siegeWait: 'Siege stages rise while you wait at home',
    tabs: { guide: 'Growth', daily: 'Daily' },
    guide: {
      unit: (name: string, n: number) => `${name} to Lv.${n}`,
      anyLevel: (n: number) => `Any monster Lv.${n}`,
      wins: (n: number) => `Win ${n} raids`,
      castle: (n: number) => `Castle Lv.${n}`,
      filled: (n: number) => `Fill ${n} monster slots`,
      idle: 'Claim idle rewards',
      summon: (n: number) => `Summon ${n} time(s)`,
      siege: (n: number) => `Siege stage ${n}`,
      stars: (n: number) => `${n} awaken star(s)`,
    },
    daily: {
      sortie: (n: number) => `Sortie ${n} times`,
      win: (n: number) => `Win ${n} raid(s)`,
      upgrade: (n: number) => `Upgrade ${n} times`,
      idle: () => 'Claim idle rewards',
    },
  },
  up: {
    one: '×1', ten: '×10', max: 'Max',
    nextFloor: (n: number) => `Next: floor ${n} opens`,
    nextUnit: (name: string) => `Next: ${name} joins`,
    nextLord: 'Next: stronger Demon Lord',
    lordShort: '×1.1 per star',
    heroBonus: (p: number) => `Loot·Defense +${p}%`,
    awaken: 'Awaken', recruit: 'Recruit', maxLv: 'Max',
    nextLevel: 'Next level',
    info: 'Details',
  },
  castleHint: 'More slots and floors, stronger lord',
  diff: { easy: 'Easy', normal: 'Normal', hard: 'Hard' } as Record<'easy' | 'normal' | 'hard', string>,
  again: 'Raid again',
  rec: 'Pick',
  unlocks: { heroes: 'Unlocked: Heroes — your raid party that attacks other castles', summon: 'Unlocked: Summon — spend soulstones on monster gear looks', awaken: 'Unlocked: Awakening — at level 50, add stars to grow stronger' } as Record<string, string>,
  heroIntro: 'Heroes = your raid party that attacks other castles · leveling them also raises your castle defense',
  heroRole: { knight: 'Holds the front and draws enemy attacks', archer: 'Shoots from the back (sometimes twice)', priest: 'Heals hurt allies' } as Record<string, string>,
  spend: { title: 'Season spending', claim: 'Claim', done: 'All tiers reached', look: 'Limited look', got: (name: string) => `New look: ${name}!` },
  shop: { valuePct: (p: number) => `${p}% value`, firstX2: 'First buy ×2', title: "Demon Lord's Vault", once: 'One time', season: 'This season', best: 'BEST', tabs: { soul: 'Soulstones', gold: 'Gold', special: 'Special' } as Record<'soul' | 'gold' | 'special', string> },
  idleBtn: 'Idle loot',
  claimIdle: (g: number) => `Collect idle income (+${F(g)})`,
  sortie: 'Raid',
  introSortie: 'Raid for revenge',
  resume: 'A raid is still in progress',
  resumeBtn: 'Resume',
  throne: 'Throne',
  floor: (n: number) => `Floor ${n}`,
  emptySlot: 'Empty',
  clearSlot: 'Clear',
  placedAt: (n: number) => `F${n}`,
  logTitle: 'Defense log',
  logDefended: (name: string) => `Held off ${name}`,
  logRobbed: (name: string, g: number) => (g > 0 ? `Robbed by ${name} (−${F(g)})` : `Robbed by ${name}`),
  ult: { knight: 'Shield Charge', archer: 'Arrow Rain', priest: 'Blessing' } as Record<string, string>,
  giveUp: 'Give up',
  confirmGiveUp: 'Give up this raid? You get no loot gold.',
  revive: (n: number) => `Revive (${n} left)`,
  victory: 'Conquered!',
  defeat: 'Wiped out',
  toHome: 'Home',
  npcTag: 'NPC',
  power: 'Power',
  estLoot: 'Est. loot',
  speed: (x: number) => `${x}×`,
  throneFloor: 'Throne room',
  loot: 'Loot',
  honor: 'Honor',
  tabs: { upgrade: 'Upgrade', log: 'Log', league: 'League', shop: 'Shop' },
  panels: { match: 'Who do we rob?', upgrade: 'Upgrade', log: 'Log', league: 'League', shop: 'Shop', settings: 'Settings' } as Record<string, string>,
  lockedFloor: (lv: number) => `Opens at castle Lv.${lv}`,
  logEmpty: 'Nobody has come yet',
  ok: 'OK',
  close: 'Close',
  editFloor: 'Squad',
  floorEditTitle: (n: number) => `Floor ${n} squad`,
  save: 'Save',
  cancel: 'Cancel',
  none: 'None',
  level: (n: number) => `Lv.${n}`,
  upgradeBtn: (cost: number) => `Upgrade (${F(cost)} gold)`,
  maxLevel: 'Max level',
  castleLevel: (n: number) => `Castle level ${n}`,
  lordLevel: (n: number) => `Demon Lord Lv.${n}`,
  recruitSoul: (soul: number) => `Recruit (${soul} soulstones)`,
  monstersTitle: 'Monsters',
  heroesTitle: 'Heroes',
  recruitTitle: 'Recruit',
  revengeBtn: 'Revenge',
  raidedLive: (name: string, g: number) => `${name} robbed your castle (−${F(g)})`,
  defendedLive: (name: string) => `Held off ${name}`,
  shopTitle: 'Shop',
  buyFor: (vx: number) => `${vx} VX`,
  purchased: 'Purchased',
  products: {
    starter_pack: ['Starter Pack', 'Necromancer + gold + 30 soulstones'],
    season_pass: ['Season Pass', 'Pass track on the season rewards + Black Dragon look at tier 10 (permanent, Demon Lord +10%)'],
    speed_x3: ['3× Speed', 'Raids and sieges play 3× faster (permanent)'],
    premium: ['Premium Pass', 'Rewards with no ads + 3x raid & siege speed + 360 soulstones (permanent)'],
    gold_pouch: ['Gold Pouch', 'Gold'],
    gold_chest: ['Gold Chest', 'Gold'],
    gold_coffer: ['Golden Coffer', 'Gold'],
    gold_vault: ["Demon Lord's Vault", 'Gold'],
    soul_pouch: ['Soulstone Pouch', 'Soulstones'],
    soul_sack: ['Soulstone Sack', 'Soulstones'],
    soul_chest: ['Soulstone Chest', 'Soulstones'],
    soul_altar: ['Soulstone Altar', 'Soulstones'],
    soul_relic: ['Soulstone Relic', 'Soulstones'],
  } as Record<string, [string, string]>,
  goldPackDesc: (gold: number, bonus: number) => (bonus > 0 ? `${F(gold)} gold · ${bonus}% more` : `${F(gold)} gold`),
  soulPackDesc: (soul: number, bonus: number) => (bonus > 0 ? `${F(soul)} soulstones · ${bonus}% more` : `${F(soul)} soulstones`),
  sortieInfo: (left: number, total: number, lord: number, lordCap: number) => `Sorties today ${left}/${total} · Lord-kill soulstones ${lord}/${lordCap}`,
  buyTicket: (gold: number) => `Buy a ticket (${F(gold)} gold)`,
  goldForSoul: (soul: number) => `${F(soul)} soulstones`,
  gainGold: (n: number) => `+${F(n)} gold`,
  gainSoul: (n: number) => `+${F(n)} soulstones`,
  buyStarter: 'See Starter Pack',
  starterDesc: (gold: number) => `Necromancer + ${F(gold)} gold + 30 soulstones`,
  leagueTitle: (id: string) => `Season ${id.slice(1)}`,
  endsIn: (ms: number) => `Ends in ${Math.max(0, Math.floor(ms / 86_400_000))}d ${Math.max(0, Math.floor((ms % 86_400_000) / 3_600_000))}h`,
  myHonor: (h: number) => `My honor ${h}`,
  bracketTitle: 'My bracket (30 players)',
  seasonReward: (a: number, b: number, c: number, d: number) => `Season-end rewards (bracket rank): 1st ${a} soulstones · 2nd–3rd ${b} · 4th–10th ${c} · others ${d}`,
  honorHow: 'Honor: raid win 10 · Demon Lord slain +5 · revenge ×2 · defense 3',
  topTitle: 'Global top 20',
  globalReward: 'Global rank rewards: 1st the “Overlord” title and the Hall of Fame · 2nd–3rd a title and the Hall of Fame · 4th–10th a title (shown all next season)',
  hallTitle: 'Hall of Fame',
  hallSeason: (id: string) => `Season ${id.slice(1)}`,
  titles: { champion: 'Overlord', top3: 'Top 3', top10: 'Top 10' } as Record<string, string>,
  noBracket: 'Win your first raid to join a bracket',
  stats: { hp: 'HP', atk: 'ATK', def: 'DEF', spd: 'SPD' },
  skills: {
    taunt: (cd: number) => `Taunt: every ${cd} attacks, draws enemy attacks for 2 seconds`,
    pierce: (cd: number) => `Pierce: every ${cd} attacks, slashes ignoring half of the defense`,
    backline: () => 'Ambush (passive): goes for the back row first',
    web: (cd: number) => `Web: every ${cd} attacks, slows one enemy for 2 seconds`,
    raise: () => 'Raise (passive): brings back the first fallen ally once at 30% HP',
    breath: (cd: number) => `Fire Breath: every ${cd} attacks, burns all enemies (60%)`,
    thorns: () => 'Spiked Rock (always): reflects 30% of damage taken back to the attacker',
    scream: (cd: number) => `Scream: every ${cd} attacks, stuns one enemy for 1 second`,
    lifesteal: () => 'Lifesteal (always): heals for 20% of damage dealt',
    execute: (cd: number) => `Execute: every ${cd} attacks, deals 1.3× damage to the weakest enemy`,
    double_shot: (cd: number) => `Double Shot: every ${cd} attacks, shoots twice (60% each)`,
    heal: (cd: number) => `Heal: every ${cd} attacks, restores 25% HP to the most hurt ally`,
    dark_wave: (cd: number) => `Dark Wave: every ${cd} attacks, hits all enemies (80%)`,
    frenzy: (cd: number) => `Frenzy: every ${cd} attacks, claws twice (60% each)`,
    gaze: (cd: number) => `Abyss Gaze: every ${cd} attacks, hits all enemies (50%)`,
  } as Record<string, (cd: number) => string>,
  tut: {
    raidSortie: "Let's start by robbing the guild castle next door!",
    raidUlt: 'When the gauge fills, the ultimate fires on its own. Just watch!',
    raidResult: 'The gold is in!',
    placeFloor: 'Now we guard our own castle too. Tap Floor 1.',
    placeSlot: 'Put a minion in the empty spot.',
    upgradeTab: 'Spend gold to make your minions stronger!',
    upgradeOne: 'Try one upgrade.',
    matchSortie: "This time it's a real player's castle. Raid!",
    end: 'Now follow "Next" down below, my lord!',
  },
  cutscene: {
    skip: 'Skip',
    lines: [
      'Imp: "My lord, the castle upkeep is three months overdue."',
      'Imp: "The castles next door are drowning in gold… shame heroes loot them every day."',
      'Demon Lord: "…Then I shall become a hero too."',
      'Demon Lord: "By day, a hero who robs other castles,"',
      'Demon Lord: "by night, a demon lord who guards his own."',
    ],
    title: 'Hero by Day, Demon Lord by Night',
  },
  nick: {
    title: "The Demon Lord's name",
    hint: '2–8 characters: Hangul, letters, numbers',
    placeholder: 'Name',
    submit: 'That is my name',
  },
  settings: {
    title: 'Settings',
    bgm: 'Music',
    sfx: 'Sound',
    on: 'On',
    off: 'Off',
    nickname: 'Name',
    renameLeft: (n: number) => `${n} free change left`,
    rename: 'Change',
    reset: 'Reset data',
    resetWarn: 'Everything goes back to the start: castle, levels, stars, gold, soulstones, looks, VIP, purchased items (3x speed, premium, season pass and more), records and siege best. Purchased items and currency are lost and cannot be restored or refunded. Only your nickname stays, and the tutorial starts again.',
    resetType: "Type 'RESET' to confirm",
    resetWord: 'RESET',
    resetGo: 'Reset',
    resetDone: 'Data reset',
    lordLook: 'Demon Lord look',
    lookOwned: (n: number, pct: number) => `${n} looks owned · Demon Lord stats +${pct}% (applies without wearing)`,
    looks: { base: 'Default', dragon: 'Black Dragon', lava: 'Lava Lord', demon: 'Violet-Winged Fiend', summon1: 'Fallen Archfiend', hydra: 'Three-Headed Hydra', spend1: 'Crystal-Crowned Kraken', lich: 'Bone Dragon Lich King', abyss: 'One-Eyed Abyss Lord', emperor: 'Abyssal Emperor' } as Record<string, string>,
    wornFx: 'Worn effect',
    lookFx: { dragon: 'Dark Wave every 3 attacks', lava: 'Reflects 30% of damage taken', demon: 'Heals 20% of damage dealt', summon1: 'Hits the weakest foe for 2×', hydra: 'Attacks bite 3 foes at once', spend1: 'All floor monsters +10%', lich: 'Revives once at 50% HP', abyss: 'Dark Wave stuns for 1 second', emperor: 'Dark Wave deals 2× damage' } as Record<string, string>,
  },
  pass: {
    rank: 'Ranking',
    track: 'Pass',
    howTier: (n: number) => `Every ${n} honor = 1 tier`,
    tier: (n: number) => `Tier ${n}`,
    done: 'Done',
    prev: 'Previous tiers',
    next: 'Next tiers',
    dragon: 'Black Dragon',
    passOnly: 'Pass',
    claimAll: 'Claim all',
    only: 'Pass only',
    dragonKeep: 'Tier 10 · yours forever',
    ownBonus: 'Just owning it: Demon Lord stats ',
    buy: 'Buy Pass',
    value: (pct: number) => `+${pct}% vs buying soulstones`,
    got: (gold: number, soul: number, skin: boolean) =>
      `Claimed! ${[gold ? `${F(gold)} gold` : '', soul ? `${soul} soulstones` : '', skin ? 'Black Dragon look' : ''].filter(Boolean).join(' · ')}`,
  },
  stuck: {
    title: (n: number) => `Stuck at siege stage ${n}`,
    sub: 'Ways to get stronger',
    fill: (name: string) => `Put ${name} in an empty slot`,
    monster: (name: string) => `Upgrade ${name}`,
    castle: 'Upgrade the castle — big jump in Demon Lord level',
    lord: 'Awaken the Demon Lord — stronger right away with soulstones',
    hero: (name: string) => `Upgrade ${name} — siege defense +1%`,
    summon: 'Summon — gear looks give +10% stats',
    shop: 'Get soulstones — for awakening and summons',
    go: 'Go',
  },
  away: {
    title: 'While you were away',
    waves: (n: number, held: number) => `${n} attacks · ${held} held`,
    stage: (from: number, to: number) => (from === to ? `Siege stage ${from} held` : `Siege stage ${from} → ${to}`),
    gold: (g: number) => `Gold piled up +${F(g)}`,
    later: 'Later',
  },
  siege: {
    farm: (n: number) => `Siege stage ${n} (repeating)`,
    challenge: (n: number) => `Challenge stage ${n}`,
    challengeReady: 'Challenging next wave',
    breachedFarm: 'Breached! Repeating the stage below',
    stage: (n: number) => `Siege stage ${n}`,
    next: (n: number, ms: number) => `Siege stage ${n} · ${Math.floor(ms / 60_000)}:${String(Math.floor(ms / 1000) % 60).padStart(2, '0')}`,
    breached: 'Throne fell! Stage down',
    call: 'Call now',
    rankTab: 'Siege',
    best: (n: number) => `Best ${n}`,
    myBest: (n: number) => `My best: stage ${n}`,
    milestoneHint: '10 soulstones for every new best stage, more every 10 stages',
    seasonBest: (n: number) => `This season: stage ${n}`,
    seasonReward: (a: number, b: number, c: number) => `Season end soulstones: 1st ${a} · 2nd ${b} · 3rd ${c}`,
    noRank: 'No records yet',
    rankFailed: "Couldn't load the ranking",
    milestone: (soul: number) => `New siege milestone! +${soul} soulstones`,
    power: 'Power',
    heroHint: 'Your raiding party. Stronger heroes rob castles more easily',
    heroBonus: (p: number) => `Now: loot gold +${p}% · siege defense +${p}%`,
    heroNext: (p: number, next: number) => `Upgrade: loot gold & siege defense +${p}% → +${next}%`,
  },
  ads: {
    watch: (label: string) => `${label} (ad)`,
    instant: (label: string) => `${label} (instant)`,
    dismissed: 'Watch the ad to the end to get it',
    failed: "Ads aren't available right now. Try again in a moment",
    left: (n: number) => `${n} left today`,
    tomorrow: 'Come back tomorrow',
    supply: 'Daily supply',
    supplyDesc: (gold: number, soul: number) => `${F(gold)} gold + ${soul} soulstones`,
    receive: 'Claim',
    revenge: 'Revenge +1',
    revive: 'Revive',
    plain: (g: number) => `Just take +${F(g)}`,
    double: (mult: number, g: number) => `Take ${mult}× +${F(g)}`,
    got: 'Claimed!',
  },
  errors: {
    AD_PLACEMENT: 'Please try again',
    AD_LIMIT: "You've claimed everything for today",
    AD_NOT_NOW: "You can't claim this right now",
    AD_NOT_VERIFIED: "The ad couldn't be verified. Please try again",
    AD_USED: 'That ad reward was already claimed',
    NICK_LENGTH: 'Names are 2–8 characters',
    NICK_CHARS: 'Only Hangul, English letters and numbers',
    NICK_JAMO: 'Use full Hangul syllables, not single letters like ㄱ or ㅏ',
    NICK_BANNED: "That name can't be used",
    NICK_TAKEN: 'Someone already has that name',
    NICK_NO_CHANGES: 'You already used your free change',
    SKIN_NOT_OWNED: "You don't own that look",
    SIEGE_TOO_SOON: 'You can call the next wave in its last 20 seconds',
    NO_SPEED3: '3× speed is a shop item',
    PASS_NOTHING: 'Nothing to claim',
    RESET_CONFIRM: "Type 'RESET' exactly",
    RESET_IN_RAID: "You can't reset during a raid",
    ONBOARDING_ORDER: 'Please try again',
    NO_REVIVE_CREDIT: 'No revive items',
    NO_REVENGE_CREDIT: "You've used today's 3 free revenges. You need a revenge ticket",
    NO_SORTIE: 'No sortie tickets left today. You can buy more with gold',
    NO_SOUL: 'Not enough soulstones',
    MAX_STARS: 'Already fully awakened',
    AWAKEN_FIRST: 'Level 50 reached. Awaken to keep growing',
    LEVEL_FIRST: 'Reach level 50 to awaken',
    generic: 'Something went wrong. Please try again in a moment.',
  } as Record<string, string>,
  serverMsg: {
    '골드가 부족하다': 'Not enough gold',
    '영혼석이 부족하다': 'Not enough soulstones',
    '최대 레벨이다': 'Already at max level',
    '성이 최대 레벨이다': 'The castle is at max level',
    '이미 공략 중이다': 'A raid is already in progress',
    '공략 중에는 편성을 바꿀 수 없다': "You can't change squads during a raid",
    '복수 기한(24시간)이 지났다': 'The 24-hour revenge window has passed',
    '복수할 수 없는 기록이다': "You can't take revenge for this one",
    '부활은 판당 1회다': 'Only one revive per raid',
    '이미 보유한 몬스터다': 'You already own this monster',
    '다시 시도해줘': 'Please try again',
  } as Record<string, string>,
  units: {
    slime: 'Slime', skeleton: 'Skeleton', imp: 'Imp', spider: 'Spider', necro: 'Necromancer', dragon: 'Baby Dragon', golem: 'Stone Golem', banshee: 'Banshee', vampire: 'Vampire', deathknight: 'Death Knight', werewolf: 'Werewolf', mushroom: 'Plague Shroom', eye: 'Abyss Eye',
    knight: 'Knight', archer: 'Archer', priest: 'Priest', lord: 'Demon Lord',
  } as Record<string, string>,
  fx: { taunt: 'Taunt', web: 'Web', stun: 'Stun', down: 'Down', raise: 'Risen as a wraith', cleared: 'Floor cleared' } as Record<string, string>,
  names: {
    guild: 'Invader Guild',
    guildApprentice: 'Invader Guild Trainee',
    guildRookie: 'Invader Guild Rookie',
    guildTier: (n: number) => `Invader Guild Rank ${n}`,
    ghost: (n: number) => `Shadow Lord ${n}`,
    lordTag: (tag: string) => `Demon Lord #${tag}`,
  },
  load: {
    top: 'Hero by Day,',
    main: 'Demon Lord by Night',
    connect: 'Connecting to the server…',
    home: 'Loading your castle…',
    assets: 'Opening the gates…',
    tips: [
      'Tip: sieges keep going while you are away',
      'Tip: revenge wins give double honor',
      'Tip: hero upgrades raise your loot gold',
      'Tip: every new best siege stage gives soulstones',
    ],
  },
  vip: {
    level: (n: number) => `VIP ${n}`,
    none: 'Not VIP',
    toNext: (vx: number, n: number) => `${vx.toLocaleString()} VX to VIP ${n}`,
    max: 'Top rank',
    nextTitle: 'Next rank',
    idle: (p: number) => `Idle income +${p}%`,
    away: (m: number) => `Away siege gold ×${m}`,
    cap: (h: number) => `Idle cap ${h}h`,
    pack: (p: number) => `Gold packs +${p}%`,
    idleAd: (n: number) => `1.5× idle ad ${n}/day`,
    revenge: (n: number) => `Free revenge ${n}/day`,
    nickname: '+1 free name change',
    skin: (name: string) => `Exclusive look: ${name}`,
    aura: 'Ruby aura',
    skins: { lava: 'Lava Lord', demon: 'Violet-Winged Fiend' } as Record<string, string>,
  },
  awaken: {
    upTab: 'Upgrade',
    tab: 'Awaken',
    hint: 'Each star multiplies all stats by 1.1. Costs soulstones and stays after a reset.',
    btn: (soul: number) => `Awaken (${F(soul)} soulstones)`,
    max: 'Fully awakened',
    lordHint: 'Separate from castle level, ×1.1 stats per star',
    mult: (now: string, next: string | null) => (next ? `Stats ×${now} → ×${next}` : `Stats ×${now}`),
    buySoul: 'Get soulstones',
  },
  news: {
    vip10: (name: string) => `${name} reached VIP 10!`,
    star20: (name: string) => `${name} reached five gold stars!`,
    champion: (name: string) => `${name} finished last season 1st overall and became the Overlord!`,
  } as Record<string, (name: string) => string>,
  summon: {
    open: 'Summon',
    pity: (n: number) => `Epic+ in ${n}`,
    legendPity: (n: number) => `Legend in ${n}`,
    rates: 'Rates',
    one: '1×',
    ten: '10+1×',
    result: 'Summon results',
    ok: 'OK',
    skipAnim: 'Skip animation',
    skip: 'Show all',
    fresh: 'NEW',
    look: (name: string) => `Look: ${name}`,
    baseLook: 'Default',
    wearWhere: 'Wear your looks from each monster in the Upgrade window',
    ratesTitle: 'Summon rates',
    grades: { common: 'Common', rare: 'Rare', epic: 'Epic', legend: 'Legendary' },
    rewardOf: { common: '10 soulstones', rare: '30 soulstones', epic: 'One of 12 monster gear looks', legend: 'One of 2 summon-only Demon Lord looks' },
    tenNote: '10+1 guarantees at least one Epic or better.',
    pityNote: (n: number) => `Your ${n}th summon without an Epic or better is guaranteed Epic or better. The count restarts whenever one drops.`,
    legendPityNote: (n: number) => `Your ${n}th summon without a Legend is guaranteed Legend. The count restarts whenever one drops.`,
    dupNote: (epic: number, legend: number) => `A look you already own turns into soulstones (Epic ${epic}, Legendary ${F(legend)}).`,
    gear: {
      'slime:crown': 'Slime King', 'slime:helm': 'Knight Slime', 'skeleton:royal': 'Skeleton King', 'skeleton:dread': 'Dread Armor',
      'imp:king': 'Imp King', 'imp:warlock': 'Warlock Imp', 'necro:lich': 'Lich King', 'necro:bone': 'Bone Armor',
      'spider:iron': 'Iron Spider', 'spider:crown': 'Spider Queen', 'dragon:knight': 'Knight Dragon', 'dragon:royal': 'Royal Dragon',
    } as Record<string, string>,
  },
  lang: { title: 'Language', pick: 'Choose your language', go: 'Start' },
};
