import { formatNum as F } from '../../server/src/growth';
import type { Strings } from './ko';

/** English. 모양은 ko.ts(Strings)와 같다 */
export const en: Strings = {
  connecting: 'Connecting to the server…',
  loading: 'Loading…',
  gold: 'Gold',
  soul: 'Soulstones',
  claimIdle: (g: number) => `Collect idle income (+${F(g)})`,
  sortie: 'Raid',
  introSortie: 'Raid for revenge',
  resume: 'A raid is still in progress',
  resumeBtn: 'Resume',
  throne: 'Throne',
  floor: (n: number) => `Floor ${n}`,
  emptySlot: 'Empty',
  clearSlot: 'Clear',
  logTitle: 'Defense log',
  logDefended: (name: string) => `Held off ${name}`,
  logRobbed: (name: string, g: number) => (g > 0 ? `Robbed by ${name} (−${F(g)})` : `Robbed by ${name}`),
  ult: { knight: 'Shield Charge', archer: 'Arrow Rain', priest: 'Blessing' } as Record<string, string>,
  giveUp: 'Give up',
  confirmGiveUp: 'Give up this raid? You get no loot.',
  revive: (n: number) => `Revive (${n} left)`,
  victory: 'Conquered!',
  defeat: 'Wiped out',
  toHome: 'Home',
  npcTag: 'NPC',
  power: 'Power',
  estLoot: 'Est. loot',
  speed: (x: number) => `${x}×`,
  throneFloor: 'Throne room',
  loot: 'Loot',
  honor: 'Honor',
  tabs: { upgrade: 'Upgrade', log: 'Log', league: 'League', shop: 'Shop' },
  panels: { match: 'Who do we rob?', upgrade: 'Upgrade', log: 'Log', league: 'League', shop: 'Shop', settings: 'Settings' } as Record<string, string>,
  lockedFloor: (lv: number) => `Castle Lv.${lv}`,
  logEmpty: 'Nobody has come yet',
  ok: 'OK',
  close: 'Close',
  editFloor: 'Squad',
  floorEditTitle: (n: number) => `Floor ${n} squad`,
  save: 'Save',
  cancel: 'Cancel',
  none: 'None',
  level: (n: number) => `Lv.${n}`,
  upgradeBtn: (cost: number) => `Upgrade (${F(cost)} gold)`,
  maxLevel: 'Max level',
  castleLevel: (n: number) => `Castle level ${n}`,
  lordLevel: (n: number) => `Demon Lord Lv.${n}`,
  recruitSoul: (soul: number) => `Recruit (${soul} soulstones)`,
  monstersTitle: 'Monsters',
  heroesTitle: 'Heroes',
  recruitTitle: 'Recruit',
  revengeBtn: 'Revenge',
  raidedLive: (name: string, g: number) => `${name} robbed your castle (−${F(g)})`,
  defendedLive: (name: string) => `Held off ${name}`,
  shopTitle: 'Shop',
  buyFor: (vx: number) => `${vx} VX`,
  purchased: 'Purchased',
  products: {
    starter_pack: ['Starter Pack', 'Necromancer + gold + 30 soulstones'],
    recruit_dragon: ['Recruit Baby Dragon', 'A baby dragon that breathes fire on every enemy (also available for soulstones)'],
    season_pass: ['Season Pass', 'Pass track on the season rewards + a limited Demon Lord look'],
    speed_x3: ['3× Speed', 'Raids and sieges play 3× faster (permanent)'],
    premium: ['Premium Pass', 'Rewards instantly with no ads (same daily limits, permanent)'],
  } as Record<string, [string, string]>,
  buyStarter: 'See Starter Pack',
  starterDesc: (gold: number) => `Necromancer + ${F(gold)} gold + 30 soulstones`,
  leagueTitle: (id: string) => `Season ${id.slice(1)}`,
  endsIn: (ms: number) => `Ends in ${Math.max(0, Math.floor(ms / 86_400_000))}d ${Math.max(0, Math.floor((ms % 86_400_000) / 3_600_000))}h`,
  myHonor: (h: number) => `My honor ${h}`,
  bracketTitle: 'My bracket (30 players)',
  seasonReward: (a: number, b: number, c: number, d: number) => `Season-end rewards (bracket rank): 1st ${a} soulstones · 2nd–3rd ${b} · 4th–10th ${c} · others ${d}`,
  honorHow: 'Honor: raid win 10 · Demon Lord slain +5 · revenge ×2 · defense 3',
  topTitle: 'Global top 20',
  noBracket: 'Win your first raid to join a bracket',
  stats: { hp: 'HP', atk: 'ATK', def: 'DEF', spd: 'SPD' },
  skills: {
    taunt: (cd: number) => `Taunt: every ${cd} turns, draws enemy attacks for 2 turns`,
    pierce: (cd: number) => `Pierce: every ${cd} turns, slashes ignoring half of the defense`,
    backline: () => 'Ambush (passive): goes for the back row first',
    web: (cd: number) => `Web: every ${cd} turns, slows one enemy for 2 turns`,
    raise: () => 'Raise (passive): brings back the first fallen ally once at 30% HP',
    breath: (cd: number) => `Fire Breath: every ${cd} turns, burns all enemies (60%)`,
    double_shot: (cd: number) => `Double Shot: every ${cd} turns, shoots twice (60% each)`,
    heal: (cd: number) => `Heal: every ${cd} turns, restores 25% HP to the most hurt ally`,
    dark_wave: (cd: number) => `Dark Wave: every ${cd} turns, hits all enemies (80%)`,
  } as Record<string, (cd: number) => string>,
  tut: {
    raidSortie: "Let's start by robbing the guild castle next door!",
    raidUlt: 'When the gauge fills, the ultimate fires on its own. Just watch!',
    raidResult: 'The gold is in!',
    placeFloor: 'Now we guard our own castle too. Tap Floor 1.',
    placeSlot: 'Put a minion in the empty spot.',
    upgradeTab: 'Spend gold to make your minions stronger!',
    upgradeOne: 'Try one upgrade.',
    matchSortie: "This time it's a real player's castle. Raid!",
    end: "The rest is up to you, my lord. (Tap to start)",
  },
  cutscene: {
    skip: 'Skip',
    lines: [
      'Imp: "My lord, the castle upkeep is three months overdue."',
      'Imp: "The castles next door are drowning in gold… shame heroes loot them every day."',
      'Demon Lord: "…Then I shall become a hero too."',
      'Demon Lord: "By day, a hero who robs other castles,"',
      'Demon Lord: "by night, a demon lord who guards his own."',
    ],
    title: 'Hero by Day, Demon Lord by Night',
  },
  nick: {
    title: "The Demon Lord's name",
    hint: '2–8 characters: Hangul, letters, numbers',
    placeholder: 'Name',
    submit: 'That is my name',
  },
  settings: {
    title: 'Settings',
    bgm: 'Music',
    sfx: 'Sound',
    on: 'On',
    off: 'Off',
    nickname: 'Name',
    renameLeft: (n: number) => `${n} free change left`,
    rename: 'Change',
    reset: 'Reset data',
    resetWarn: 'Your castle, levels, gold, soulstones, log and this season’s honor go back to the start. Paid monsters, 2× idle, the season pass, leftover items, your name and your best siege record stay. You will play the tutorial again. This cannot be undone.',
    resetType: "Type 'RESET' to confirm",
    resetWord: 'RESET',
    resetGo: 'Reset',
    resetDone: 'Data reset',
    lordLook: 'Demon Lord look',
    looks: { base: 'Default', skull: 'Skull Sovereign', dragon: 'Black Dragon' } as Record<string, string>,
  },
  pass: {
    rank: 'Ranking',
    track: 'Pass',
    tier: (n: number) => `Tier ${n}`,
    done: 'Done',
    prev: 'Previous tiers',
    next: 'Next tiers',
    dragon: 'Black Dragon',
    passOnly: 'Pass',
    claimAll: 'Claim all',
    got: (gold: number, soul: number, skin: boolean) =>
      `Claimed! ${[gold ? `${F(gold)} gold` : '', soul ? `${soul} soulstones` : '', skin ? 'Black Dragon look' : ''].filter(Boolean).join(' · ')}`,
  },
  away: {
    title: 'While you were away',
    waves: (n: number, held: number) => `${n} attacks · ${held} held`,
    stage: (from: number, to: number) => `Siege stage ${from} → ${to}`,
    gold: (g: number) => `Gold piled up +${F(g)}`,
    later: 'Later',
  },
  siege: {
    stage: (n: number) => `Siege stage ${n}`,
    next: (n: number, ms: number) => `Siege stage ${n} · ${Math.floor(ms / 60_000)}:${String(Math.floor(ms / 1000) % 60).padStart(2, '0')}`,
    breached: 'Throne fell! Stage down',
    call: 'Call now',
    rankTab: 'Siege',
    best: (n: number) => `Best ${n}`,
    myBest: (n: number) => `My best: stage ${n}`,
    milestoneHint: 'Soulstones the first time you pass every 10th stage',
    noRank: 'No records yet',
    rankFailed: "Couldn't load the ranking",
    milestone: (soul: number) => `New siege milestone! +${soul} soulstones`,
    power: 'Power',
    heroHint: 'Each hero level: +1% loot · +1% siege defense',
  },
  ads: {
    watch: (label: string) => `${label} (ad)`,
    instant: (label: string) => `${label} (instant)`,
    dismissed: 'Watch the ad to the end to get it',
    failed: "Ads aren't available right now. Try again in a moment",
    left: (n: number) => `${n} left today`,
    tomorrow: 'Come back tomorrow',
    supply: 'Daily supply',
    supplyDesc: (gold: number, soul: number) => `${F(gold)} gold + ${soul} soulstones`,
    receive: 'Claim',
    revenge: 'Revenge +1',
    revive: 'Revive',
    plain: (g: number) => `Just take +${F(g)}`,
    double: (mult: number, g: number) => `Take ${mult}× +${F(g)}`,
    got: 'Claimed!',
  },
  errors: {
    AD_PLACEMENT: 'Please try again',
    AD_LIMIT: "You've claimed everything for today",
    AD_NOT_NOW: "You can't claim this right now",
    AD_NOT_VERIFIED: "The ad couldn't be verified. Please try again",
    AD_USED: 'That ad reward was already claimed',
    NICK_LENGTH: 'Names are 2–8 characters',
    NICK_CHARS: 'Only Hangul, English letters and numbers',
    NICK_JAMO: 'Use full Hangul syllables, not single letters like ㄱ or ㅏ',
    NICK_BANNED: "That name can't be used",
    NICK_TAKEN: 'Someone already has that name',
    NICK_NO_CHANGES: 'You already used your free change',
    SKIN_NOT_OWNED: "You don't own that look",
    SIEGE_TOO_SOON: 'You can call the next wave in its last 20 seconds',
    NO_SPEED3: '3× speed is a shop item',
    PASS_NOTHING: 'Nothing to claim',
    RESET_CONFIRM: "Type 'RESET' exactly",
    RESET_IN_RAID: "You can't reset during a raid",
    ONBOARDING_ORDER: 'Please try again',
    NO_REVIVE_CREDIT: 'No revive items',
    NO_REVENGE_CREDIT: "You've used today's 3 free revenges. You need a revenge ticket",
    generic: 'Something went wrong. Please try again in a moment.',
  } as Record<string, string>,
  serverMsg: {
    '골드가 부족하다': 'Not enough gold',
    '영혼석이 부족하다': 'Not enough soulstones',
    '최대 레벨이다': 'Already at max level',
    '성이 최대 레벨이다': 'The castle is at max level',
    '이미 공략 중이다': 'A raid is already in progress',
    '공략 중에는 편성을 바꿀 수 없다': "You can't change squads during a raid",
    '복수 기한(24시간)이 지났다': 'The 24-hour revenge window has passed',
    '복수할 수 없는 기록이다': "You can't take revenge for this one",
    '부활은 판당 1회다': 'Only one revive per raid',
    '이미 보유한 몬스터다': 'You already own this monster',
    '다시 시도해줘': 'Please try again',
  } as Record<string, string>,
  units: {
    slime: 'Slime', skeleton: 'Skeleton', imp: 'Imp', spider: 'Spider', necro: 'Necromancer', dragon: 'Baby Dragon',
    knight: 'Knight', archer: 'Archer', priest: 'Priest', lord: 'Demon Lord',
  } as Record<string, string>,
  fx: { taunt: 'Taunt', web: 'Web', stun: 'Stun', down: 'Down', raise: 'Risen as a wraith', cleared: 'Floor cleared' } as Record<string, string>,
  names: {
    guild: 'Invader Guild',
    guildApprentice: 'Invader Guild Trainee',
    guildRookie: 'Invader Guild Rookie',
    guildTier: (n: number) => `Invader Guild Rank ${n}`,
    ghost: (n: number) => `Shadow Lord ${n}`,
    lordTag: (tag: string) => `Demon Lord #${tag}`,
  },
  lang: { title: 'Language', pick: 'Choose your language', go: 'Start' },
};
