import { formatNum as F } from '../../server/src/growth';
import type { Strings } from './ko';

/** 日本語. 모양은 ko.ts(Strings)와 같다 */
export const ja: Strings = {
  connecting: 'サーバーに接続中…',
  loading: '読み込み中…',
  gold: 'ゴールド',
  soul: '魂石',
  claimIdle: (g: number) => `放置収入を受け取る (+${F(g)})`,
  sortie: '出撃',
  introSortie: '復讐に出撃',
  resume: '進行中の攻略がある',
  resumeBtn: '再開',
  throne: '玉座',
  floor: (n: number) => `${n}階`,
  emptySlot: '空き',
  clearSlot: '外す',
  logTitle: '防衛記録',
  logDefended: (name: string) => `${name}の侵入を防いだ`,
  logRobbed: (name: string, g: number) => (g > 0 ? `${name}に奪われた (−${F(g)})` : `${name}に奪われた`),
  ult: { knight: 'シールドチャージ', archer: '矢の雨', priest: '祝福' } as Record<string, string>,
  giveUp: '撤退',
  confirmGiveUp: '攻略をあきらめる？略奪ゴールドはない。',
  revive: (n: number) => `復活 (所持 ${n})`,
  victory: '陥落！',
  defeat: '全滅',
  toHome: 'ホームへ',
  npcTag: 'NPC',
  power: '戦闘力',
  estLoot: '予想略奪',
  speed: (x: number) => `${x}×`,
  throneFloor: '玉座の間',
  loot: '略奪',
  honor: '名誉',
  tabs: { upgrade: '強化', log: '記録', league: 'リーグ', shop: 'ショップ' },
  panels: { match: '誰を襲う？', upgrade: '強化', log: '記録', league: 'リーグ', shop: 'ショップ', settings: '設定' } as Record<string, string>,
  lockedFloor: (lv: number) => `城 Lv.${lv}`,
  logEmpty: 'まだ誰も来ていない',
  ok: 'OK',
  close: '閉じる',
  editFloor: '編成',
  floorEditTitle: (n: number) => `${n}階の編成`,
  save: '保存',
  cancel: 'キャンセル',
  none: 'なし',
  level: (n: number) => `Lv.${n}`,
  upgradeBtn: (cost: number) => `強化 (${F(cost)} ゴールド)`,
  maxLevel: '最大レベル',
  castleLevel: (n: number) => `城レベル ${n}`,
  lordLevel: (n: number) => `魔王 Lv.${n}`,
  recruitSoul: (soul: number) => `仲間にする (魂石 ${soul})`,
  monstersTitle: 'モンスター',
  heroesTitle: '勇者',
  recruitTitle: '仲間にする',
  revengeBtn: '復讐',
  raidedLive: (name: string, g: number) => `${name}に城を襲われた (−${F(g)})`,
  defendedLive: (name: string) => `${name}の侵入を防いだ`,
  shopTitle: 'ショップ',
  buyFor: (vx: number) => `${vx} VX`,
  purchased: '購入済み',
  products: {
    starter_pack: ['スターターパック', 'ネクロマンサー + ゴールド + 魂石30'],
    season_pass: ['シーズンパス', 'シーズン報酬のパス列 + 限定魔王スキン'],
    speed_x3: ['3倍速', '攻略・攻城が3倍速く (永久)'],
    premium: ['プレミアムパス', '広告なしですぐ報酬 (1日の上限は同じ、永久)'],
    gold_pouch: ['金貨の袋', 'ゴールド'],
    gold_chest: ['金貨の箱', 'ゴールド'],
    gold_coffer: ['黄金の宝箱', 'ゴールド'],
    gold_vault: ['魔王の宝物庫', 'ゴールド'],
    soul_pouch: ['魂石の小袋', '魂石'],
    soul_sack: ['魂石の大袋', '魂石'],
    soul_chest: ['魂石の箱', '魂石'],
    soul_altar: ['魂石の祭壇', '魂石'],
    soul_relic: ['魂石の聖遺物', '魂石'],
  } as Record<string, [string, string]>,
  goldPackDesc: (gold: number, bonus: number) => (bonus > 0 ? `ゴールド ${F(gold)} · ${bonus}%お得` : `ゴールド ${F(gold)}`),
  soulPackDesc: (soul: number, bonus: number) => (bonus > 0 ? `魂石 ${F(soul)} · ${bonus}%お得` : `魂石 ${F(soul)}`),
  buyStarter: 'スターターパックを見る',
  starterDesc: (gold: number) => `ネクロマンサー + ゴールド ${F(gold)} + 魂石30`,
  leagueTitle: (id: string) => `シーズン ${id.slice(1)}`,
  endsIn: (ms: number) => `終了まで ${Math.max(0, Math.floor(ms / 86_400_000))}日 ${Math.max(0, Math.floor((ms % 86_400_000) / 3_600_000))}時間`,
  myHonor: (h: number) => `自分の名誉 ${h}`,
  bracketTitle: '自分のブラケット (30人)',
  seasonReward: (a: number, b: number, c: number, d: number) => `シーズン終了報酬 (ブラケット順位): 1位 魂石${a} · 2〜3位 ${b} · 4〜10位 ${c} · その他 ${d}`,
  honorHow: '名誉: 攻略勝利 10 · 魔王撃破 +5 · 復讐 2倍 · 防衛成功 3',
  topTitle: '全体トップ20',
  globalReward: '全体順位報酬: 1位 称号「覇王」・殿堂入り · 2〜3位 称号・殿堂入り · 4〜10位 称号（次のシーズンの間）',
  hallTitle: '殿堂',
  hallSeason: (id: string) => `シーズン${id.slice(1)}`,
  titles: { champion: '覇王', top3: 'トップ3', top10: 'トップ10' } as Record<string, string>,
  noBracket: '初めての攻略に勝つとブラケットに入る',
  stats: { hp: '体力', atk: '攻撃', def: '防御', spd: '速さ' },
  skills: {
    taunt: (cd: number) => `挑発: ${cd}ターンごとに2ターン敵の攻撃を引きつける`,
    pierce: (cd: number) => `貫通: ${cd}ターンごとに防御を半分無視して斬る`,
    backline: () => '奇襲 (常時): 後列の敵を先に狙う',
    web: (cd: number) => `蜘蛛の糸: ${cd}ターンごとに敵1体を2ターン遅くする`,
    raise: () => '蘇生 (常時): 最初に倒れた味方を一度だけ体力30%で起こす',
    breath: (cd: number) => `火炎: ${cd}ターンごとに敵全体を焼く (60%)`,
    thorns: () => 'トゲ岩（常時）: 受けたダメージの30%を攻撃した敵に返す',
    scream: (cd: number) => `悲鳴: ${cd}ターンごとに敵ひとりを1ターン気絶させる`,
    lifesteal: () => '吸血（常時）: 与えたダメージの30%だけ回復する',
    execute: (cd: number) => `処刑: ${cd}ターンごとに最も体力の低い敵に2倍ダメージ`,
    double_shot: (cd: number) => `連射: ${cd}ターンごとに2回撃つ (各60%)`,
    heal: (cd: number) => `治癒: ${cd}ターンごとに一番傷ついた味方の体力を25%回復`,
    dark_wave: (cd: number) => `暗黒波動: ${cd}ターンごとに敵全体を攻撃 (80%)`,
  } as Record<string, (cd: number) => string>,
  tut: {
    raidSortie: 'まずは隣町のギルドの城から襲いましょう！',
    raidUlt: '気がたまると必殺技が勝手に出ます。ご覧あれ！',
    raidResult: '金貨が入りました！',
    placeFloor: 'さあ、我らの城も守らねば。1階を押してください。',
    placeSlot: '空いた場所に手下を置きます。',
    upgradeTab: '金貨で手下を強く！',
    upgradeOne: '一度強化してみましょう。',
    matchSortie: '今度は本物の他人の城です。出撃！',
    end: 'あとはお任せします、魔王様。(押して開始)',
  },
  cutscene: {
    skip: 'スキップ',
    lines: [
      'インプ:「魔王様、城の維持費がもう三か月も滞っております」',
      'インプ:「隣町の魔王城は金があふれておりますが…毎日勇者に奪われて困っておるとか」',
      '魔王:「…ならば我も勇者になればよい」',
      '魔王:「昼は勇者として他人の城を襲い、」',
      '魔王:「夜は魔王として我が城を守る」',
    ],
    title: '昼は勇者、夜は魔王',
  },
  nick: {
    title: '魔王の名前',
    hint: '2〜8文字、ハングル・英字・数字',
    placeholder: '名前',
    submit: 'これに決めた',
  },
  settings: {
    title: '設定',
    bgm: 'BGM',
    sfx: '効果音',
    on: 'オン',
    off: 'オフ',
    nickname: 'ニックネーム',
    renameLeft: (n: number) => `無料変更 残り${n}回`,
    rename: '変更',
    reset: 'データ初期化',
    resetWarn: '城・レベル・ゴールド・記録・今シーズンの名誉が最初に戻ります。魂石・覚醒の星、課金で得たモンスター・放置2倍・シーズンパス・残りのアイテム、ニックネーム、攻城の最高記録は残ります。チュートリアルをもう一度行います。元に戻せません。',
    resetType: "確認のため「リセット」と入力してください",
    resetWord: 'リセット',
    resetGo: '初期化',
    resetDone: '初期化した',
    lordLook: '魔王の外見',
    looks: { base: '基本', skull: '骸骨の君主', dragon: '黒竜', lava: '溶岩の魔王', demon: '紫翼の悪魔' } as Record<string, string>,
  },
  pass: {
    rank: '順位',
    track: 'パス',
    tier: (n: number) => `${n}段階`,
    done: '完了',
    prev: '前の段階',
    next: '次の段階',
    dragon: '黒竜',
    passOnly: 'パス',
    claimAll: 'すべて受け取る',
    got: (gold: number, soul: number, skin: boolean) =>
      `受け取った！ ${[gold ? `ゴールド ${F(gold)}` : '', soul ? `魂石 ${soul}` : '', skin ? '黒竜の外見' : ''].filter(Boolean).join(' · ')}`,
  },
  away: {
    title: '留守の間に',
    waves: (n: number, held: number) => `侵入 ${n}回 · 防衛 ${held}回`,
    stage: (from: number, to: number) => `攻城 ${from}段階 → ${to}段階`,
    gold: (g: number) => `たまったゴールド +${F(g)}`,
    later: 'あとで',
  },
  siege: {
    stage: (n: number) => `攻城 ${n}段階`,
    next: (n: number, ms: number) => `攻城 ${n}段階 · ${Math.floor(ms / 60_000)}:${String(Math.floor(ms / 1000) % 60).padStart(2, '0')}`,
    breached: '玉座陥落！段階ダウン',
    call: 'すぐ呼ぶ',
    rankTab: '攻城',
    best: (n: number) => `最高 ${n}`,
    myBest: (n: number) => `自分の最高 ${n}段階`,
    milestoneHint: '10段階ごとに初めて越えると魂石',
    noRank: 'まだ記録がない',
    rankFailed: '順位を読み込めなかった',
    milestone: (soul: number) => `攻城段階を初突破！魂石 +${soul}`,
    power: '戦闘力',
    heroHint: '攻略で戦う自分のパーティー。強いほど他人の城を楽に襲える',
    heroBonus: (p: number) => `現在 略奪ゴールド +${p}% · 攻城防衛 +${p}%`,
    heroNext: (p: number) => `強化すると 略奪ゴールド・攻城防衛 +${p}% → +${p + 1}%`,
  },
  ads: {
    watch: (label: string) => `${label} (広告)`,
    instant: (label: string) => `${label} (すぐ)`,
    dismissed: '広告を最後まで見ると受け取れる',
    failed: '今は広告を見られない。少し後でもう一度',
    left: (n: number) => `今日あと${n}回`,
    tomorrow: 'また明日',
    supply: '毎日の補給',
    supplyDesc: (gold: number, soul: number) => `ゴールド ${F(gold)} + 魂石 ${soul}`,
    receive: '受け取る',
    revenge: '復讐 +1',
    revive: '復活',
    plain: (g: number) => `そのまま受け取る +${F(g)}`,
    double: (mult: number, g: number) => `${mult}倍で受け取る +${F(g)}`,
    got: '受け取った！',
  },
  errors: {
    AD_PLACEMENT: 'もう一度試してください',
    AD_LIMIT: '今日はすべて受け取った',
    AD_NOT_NOW: '今は受け取れない',
    AD_NOT_VERIFIED: '広告を確認できなかった。もう一度試してください',
    AD_USED: 'すでに受け取った広告だ',
    NICK_LENGTH: '名前は2〜8文字で',
    NICK_CHARS: 'ハングル・英字・数字のみ使える',
    NICK_JAMO: 'ㄱ・ㅏ のような字母だけは使えない。完成した文字で入力して',
    NICK_BANNED: '使えない名前だ',
    NICK_TAKEN: 'その名前はもう使われている',
    NICK_NO_CHANGES: '無料変更はもう使った',
    SKIN_NOT_OWNED: '持っていない外見だ',
    SIEGE_TOO_SOON: '次の波の20秒前から呼べる',
    NO_SPEED3: '3倍速はショップの商品だ',
    PASS_NOTHING: '受け取れる報酬がない',
    RESET_CONFIRM: '「リセット」と正確に入力して',
    RESET_IN_RAID: '攻略中は初期化できない',
    ONBOARDING_ORDER: 'もう一度試してください',
    NO_REVIVE_CREDIT: '復活アイテムがない',
    NO_REVENGE_CREDIT: '今日の無料復讐3回を使い切った。復讐券が必要だ',
    NO_SOUL: '魂石が足りない',
    MAX_STARS: 'すでに最大覚醒だ',
    generic: '問題が起きた。少し後でもう一度試してください。',
  } as Record<string, string>,
  serverMsg: {
    '골드가 부족하다': 'ゴールドが足りない',
    '영혼석이 부족하다': '魂石が足りない',
    '최대 레벨이다': 'すでに最大レベルだ',
    '성이 최대 레벨이다': '城は最大レベルだ',
    '이미 공략 중이다': 'すでに攻略中だ',
    '공략 중에는 편성을 바꿀 수 없다': '攻略中は編成を変えられない',
    '복수 기한(24시간)이 지났다': '復讐の期限 (24時間) が過ぎた',
    '복수할 수 없는 기록이다': '復讐できない記録だ',
    '부활은 판당 1회다': '復活は1回の攻略につき1回だ',
    '이미 보유한 몬스터다': 'すでに持っているモンスターだ',
    '다시 시도해줘': 'もう一度試してください',
  } as Record<string, string>,
  units: {
    slime: 'スライム', skeleton: '骸骨兵', imp: 'インプ', spider: 'クモ', necro: 'ネクロマンサー', dragon: '子ドラゴン', golem: 'ストーンゴーレム', banshee: 'バンシー', vampire: '吸血鬼', deathknight: 'デスナイト',
    knight: '騎士', archer: '弓兵', priest: '聖職者', lord: '魔王',
  } as Record<string, string>,
  fx: { taunt: '挑発', web: '蜘蛛の糸', stun: '気絶', down: 'ダウン', raise: '亡霊として復活', cleared: '階を突破' } as Record<string, string>,
  names: {
    guild: '侵入者ギルド',
    guildApprentice: '侵入者ギルド 見習い',
    guildRookie: '侵入者ギルド 新人',
    guildTier: (n: number) => `侵入者ギルド ${n}段`,
    ghost: (n: number) => `影の魔王 ${n}`,
    lordTag: (tag: string) => `魔王 #${tag}`,
  },
  load: {
    top: '昼は勇者、',
    main: '夜は魔王',
    connect: 'サーバーに接続中…',
    home: '城を読み込み中…',
    assets: '城門を開いている…',
    tips: [
      'ヒント: 攻城は留守の間も続く',
      'ヒント: 復讐すると名誉が2倍',
      'ヒント: 勇者を強化するたびに略奪ゴールド +1%',
      'ヒント: 攻城10段階ごとに初突破で魂石',
    ],
  },
  vip: {
    level: (n: number) => `VIP ${n}`,
    none: 'VIPではない',
    toNext: (vx: number, n: number) => `VIP ${n}まで ${vx.toLocaleString()} VX`,
    max: '最高ランク',
    nextTitle: '次のランク特典',
    idle: (p: number) => `放置収入 +${p}%`,
    away: (m: number) => `留守中の攻城ゴールド ×${m}`,
    cap: (h: number) => `放置の上限 ${h}時間`,
    pack: (p: number) => `ゴールドパック +${p}%`,
    idleAd: (n: number) => `広告1.5倍 1日${n}回`,
    revenge: (n: number) => `無料復讐 1日${n}回`,
    nickname: 'ニックネーム無料変更 +1',
    skin: (name: string) => `専用外見: ${name}`,
    aura: 'ルビーのオーラ',
    skins: { lava: '溶岩の魔王', demon: '紫翼の悪魔' } as Record<string, string>,
  },
  awaken: {
    upTab: '強化',
    tab: '覚醒',
    hint: '星ひとつごとに全能力×1.1。魂石を使い、リセットしても残る。',
    btn: (soul: number) => `覚醒（魂石 ${F(soul)}）`,
    max: '最大覚醒',
    mult: (now: string, next: string | null) => (next ? `能力 ×${now} → ×${next}` : `能力 ×${now}`),
    buySoul: '魂石を買う',
  },
  news: {
    vip10: (name: string) => `${name}さんがVIP 10になった！`,
    star20: (name: string) => `${name}さんが星20の覚醒を達成した！`,
    champion: (name: string) => `${name}さんが前シーズン全体1位の「覇王」になった！`,
  } as Record<string, (name: string) => string>,
  lang: { title: '言語', pick: '言語を選んでください', go: 'スタート' },
};
