export const T = {
  connecting: '서버에 연결하는 중…',
  loading: '불러오는 중…',
  gold: '골드',
  soul: '영혼석',
  claimIdle: (g: number) => `방치 수입 받기 (+${g})`,
  sortie: '출정',
  introSortie: '복수하러 출정',
  resume: '진행 중인 공략이 있다',
  resumeBtn: '이어하기',
  throne: '옥좌',
  throneEmptyBadge: '성주 부재 중',
  floor: (n: number) => `${n}층`,
  emptySlot: '빈 칸',
  logTitle: '방어 기록',
  logDefended: (name: string) => `${name}의 침입을 막았다`,
  logRobbed: (name: string, g: number) => `${name}에게 털렸다 (−${g})`,
  ult: { knight: '방패 돌진', archer: '화살비', priest: '축복' } as Record<string, string>,
  giveUp: '포기',
  confirmGiveUp: '공략을 포기할까? 전리품은 없다.',
  revive: (n: number) => `부활 (보유 ${n})`,
  victory: '함락!',
  defeat: '전멸',
  toHome: '홈으로',
  npcTag: 'NPC',
  shadowUse: (n: number) => `그림자 대역 사용 (보유 ${n})`,
  power: '전투력',
  estLoot: '예상 약탈',
  speed: (x: number) => `${x}×`,
  throneFloor: '옥좌층',
  loot: '약탈',
  honor: '명예',
  tabs: { upgrade: '강화', log: '기록', league: '리그', shop: '상점' },
  panels: { match: '누구를 털까?', upgrade: '강화', log: '기록', league: '리그', shop: '상점' } as Record<string, string>,
  lockedFloor: (lv: number) => `성 Lv.${lv}`,
  logEmpty: '아직 아무도 오지 않았다',
  ultTitle: '궁극기',
  ok: '확인',
  close: '닫기',
  tapFloorHint: '층을 눌러 몬스터 배치',
  editFloor: '편성',
  floorEditTitle: (n: number) => `${n}층 편성`,
  save: '저장',
  cancel: '취소',
  trapLabel: '함정',
  none: '없음',
  level: (n: number) => `Lv.${n}`,
  upgradeBtn: (cost: number) => `강화 (${cost} 골드)`,
  maxLevel: '최대 레벨',
  castleLevel: (n: number) => `성 레벨 ${n}`,
  recruitSoul: (soul: number) => `영입 (영혼석 ${soul})`,
  monstersTitle: '몬스터',
  heroesTitle: '용사',
  trapsTitle: '함정',
  recruitTitle: '영입',
  revengeBtn: '복수',
  raidedLive: (name: string, g: number) => `${name}가 내 성을 털었다 (−${g})`,
  defendedLive: (name: string) => `${name}의 침입을 막았다`,
  shopTitle: '상점',
  buyFor: (vx: number) => `${vx} VX`,
  purchased: '구매 완료',
  products: {
    starter_pack: ['스타터팩', '네크로맨서 + 골드 5,000 + 영혼석 30'],
    recruit_dragon: ['새끼 용 영입', '광역 화염을 뿜는 새끼 용 (영혼석으로도 얻을 수 있다)'],
    idle_x2: ['방치 배속 ×2', '방치 수입이 영원히 두 배'],
    revive: ['부활', '공략 중 전멸하면 HP 50%로 한 번 더 (판당 1회)'],
    shadow_double: ['그림자 대역', '다음 출정 동안 마왕 대역이 50% 힘으로 옥좌를 지킨다'],
    revenge_ticket: ['복수권', '오늘 무료 복수를 다 쓴 뒤 1회 더'],
    daily_supply: ['일일 보급', '골드 3,000 + 영혼석 10 (하루 1회)'],
    season_pass: ['시즌 패스', '시즌 보상 두 배 + 한정 마왕 외형'],
  } as Record<string, [string, string]>,
  buyRevive: '부활 구매',
  buyStarter: '스타터팩 보기',
  leagueTitle: (id: string) => `시즌 ${id.slice(1)}`,
  endsIn: (ms: number) => `종료까지 ${Math.max(0, Math.floor(ms / 86_400_000))}일 ${Math.max(0, Math.floor((ms % 86_400_000) / 3_600_000))}시간`,
  myHonor: (h: number) => `내 명예 ${h}`,
  bracketTitle: '내 브래킷 (30명)',
  topTitle: '전체 상위 20',
  noBracket: '첫 공략에서 이기면 브래킷에 들어간다',
  errors: {
    NO_REVIVE_CREDIT: '부활 아이템이 없다',
    NO_REVENGE_CREDIT: '오늘 무료 복수 3회를 다 썼다. 복수권이 필요하다',
    generic: '문제가 생겼다. 잠시 후 다시 시도해줘.',
  } as Record<string, string>,
};
