export const T = {
  connecting: '서버에 연결하는 중…',
  loading: '불러오는 중…',
  gold: '골드',
  soul: '영혼석',
  claimIdle: (g: number) => `방치 수입 받기 (+${g})`,
  sortie: '출정',
  introSortie: '복수하러 출정',
  resume: '진행 중인 공략이 있다',
  resumeBtn: '이어하기',
  throne: '옥좌',
  floor: (n: number) => `${n}층`,
  emptySlot: '빈 칸',
  logTitle: '방어 기록',
  logDefended: (name: string) => `${name}의 침입을 막았다`,
  logRobbed: (name: string, g: number) => (g > 0 ? `${name}에게 털렸다 (−${g})` : `${name}에게 털렸다`),
  ult: { knight: '방패 돌진', archer: '화살비', priest: '축복' } as Record<string, string>,
  giveUp: '포기',
  confirmGiveUp: '공략을 포기할까? 전리품은 없다.',
  revive: (n: number) => `부활 (보유 ${n})`,
  victory: '함락!',
  defeat: '전멸',
  toHome: '홈으로',
  npcTag: 'NPC',
  power: '전투력',
  estLoot: '예상 약탈',
  speed: (x: number) => `${x}×`,
  throneFloor: '옥좌층',
  loot: '약탈',
  honor: '명예',
  tabs: { upgrade: '강화', log: '기록', league: '리그', shop: '상점' },
  panels: { match: '누구를 털까?', upgrade: '강화', log: '기록', league: '리그', shop: '상점', settings: '설정' } as Record<string, string>,
  lockedFloor: (lv: number) => `성 Lv.${lv}`,
  logEmpty: '아직 아무도 오지 않았다',
  ultTitle: '궁극기',
  ok: '확인',
  close: '닫기',
  editFloor: '편성',
  floorEditTitle: (n: number) => `${n}층 편성`,
  save: '저장',
  cancel: '취소',
  trapLabel: '함정',
  none: '없음',
  level: (n: number) => `Lv.${n}`,
  upgradeBtn: (cost: number) => `강화 (${cost} 골드)`,
  maxLevel: '최대 레벨',
  castleLevel: (n: number) => `성 레벨 ${n}`,
  recruitSoul: (soul: number) => `영입 (영혼석 ${soul})`,
  monstersTitle: '몬스터',
  heroesTitle: '용사',
  trapsTitle: '함정',
  recruitTitle: '영입',
  revengeBtn: '복수',
  raidedLive: (name: string, g: number) => `${name}가 내 성을 털었다 (−${g})`,
  defendedLive: (name: string) => `${name}의 침입을 막았다`,
  shopTitle: '상점',
  buyFor: (vx: number) => `${vx} VX`,
  purchased: '구매 완료',
  products: {
    starter_pack: ['스타터팩', '네크로맨서 + 골드 5,000 + 영혼석 30'],
    recruit_dragon: ['새끼 용 영입', '광역 화염을 뿜는 새끼 용 (영혼석으로도 얻을 수 있다)'],
    season_pass: ['시즌 패스', '시즌 보상 트랙 패스 줄 + 한정 마왕 외형'],
    speed_x3: ['3배속', '공략을 3배 빠르게 (영구)'],
    premium: ['프리미엄 패스', '광고 없이 바로 보상 (하루 한도는 같음, 영구)'],
  } as Record<string, [string, string]>,
  buyStarter: '스타터팩 보기',
  leagueTitle: (id: string) => `시즌 ${id.slice(1)}`,
  endsIn: (ms: number) => `종료까지 ${Math.max(0, Math.floor(ms / 86_400_000))}일 ${Math.max(0, Math.floor((ms % 86_400_000) / 3_600_000))}시간`,
  myHonor: (h: number) => `내 명예 ${h}`,
  bracketTitle: '내 브래킷 (30명)',
  topTitle: '전체 상위 20',
  noBracket: '첫 공략에서 이기면 브래킷에 들어간다',
  tut: {
    raidSortie: '우선 옆 동네 길드 성부터 털어 봅시다!',
    raidUlt: '기가 모이면 궁극기! 지금 눌러 보십쇼.',
    raidResult: '금화가 들어왔습니다!',
    placeFloor: '이제 우리 성도 지켜야지요. 1층을 눌러 보십쇼.',
    placeSlot: '빈 자리에 부하를 세웁니다.',
    upgradeTab: '금화로 부하를 강하게!',
    upgradeOne: '한 번 강화해 보시지요.',
    matchSortie: '이번엔 진짜 남의 성입니다. 출정!',
    end: '이제 알아서 하십쇼, 마왕님. (눌러서 시작)',
  },
  cutscene: {
    skip: '건너뛰기',
    lines: [
      '임프: "마왕님, 성 유지비가 석 달째 밀렸습니다."',
      '임프: "옆 동네 마왕성들은 금이 넘친답니다… 용사들이 매일 털어 가서 문제지요."',
      '마왕: "…그럼 나도 용사가 되면 되겠군."',
      '마왕: "낮엔 용사로 남의 성을 털고,"',
      '마왕: "밤엔 마왕으로 내 성을 지킨다."',
    ],
    title: '낮엔 용사, 밤엔 마왕',
  },
  nick: {
    title: '마왕의 이름',
    hint: '2~8자, 한글·영문·숫자',
    placeholder: '이름',
    submit: '이걸로 정한다',
  },
  settings: {
    title: '설정',
    bgm: '배경음',
    sfx: '효과음',
    on: '켜기',
    off: '끄기',
    nickname: '닉네임',
    renameLeft: (n: number) => `무료 변경 ${n}회 남음`,
    rename: '변경',
    reset: '데이터 초기화',
    resetWarn: '성·레벨·골드·영혼석·기록·이번 시즌 명예가 처음으로 돌아갑니다. 결제로 얻은 몬스터·방치 2배·시즌 패스·남은 아이템과 닉네임은 남습니다. 되돌릴 수 없습니다.',
    resetType: "확인하려면 '초기화'를 입력하세요",
    resetGo: '초기화',
    resetDone: '초기화했다',
  },
  ads: {
    watch: (label: string) => `${label} (광고)`,
    instant: (label: string) => `${label} (바로)`,
    dismissed: '광고를 끝까지 봐야 받을 수 있다',
    failed: '지금은 광고를 볼 수 없다. 잠시 후 다시 시도해줘',
    left: (n: number) => `오늘 ${n}회 남음`,
    tomorrow: '내일 다시',
    supply: '일일 보급',
    supplyDesc: '골드 5,000 + 영혼석 15',
    receive: '받기',
    revenge: '복수 +1',
    revive: '부활',
    plain: (g: number) => `그냥 받기 +${g}`,
    double: (g: number) => `2배 받기 +${g}`,
    got: '받았다!',
  },
  errors: {
    AD_PLACEMENT: '다시 시도해줘',
    AD_LIMIT: '오늘은 다 받았다',
    AD_NOT_NOW: '지금은 받을 수 없다',
    AD_NOT_VERIFIED: '광고 확인이 안 됐다. 다시 시도해줘',
    AD_USED: '이미 받은 광고다',
    AD_VERIFY_UNAVAILABLE: '지금은 광고 보상을 받을 수 없다',
    NICK_LENGTH: '이름은 2~8자로 정해줘',
    NICK_CHARS: '한글·영문·숫자만 쓸 수 있다',
    NICK_BANNED: '쓸 수 없는 이름이다',
    NICK_TAKEN: '이미 누가 쓰는 이름이다',
    NICK_NO_CHANGES: '무료 변경을 이미 썼다',
    RESET_CONFIRM: "'초기화'를 정확히 입력해줘",
    RESET_IN_RAID: '공략 중에는 초기화할 수 없다',
    ONBOARDING_ORDER: '다시 시도해줘',
    NO_REVIVE_CREDIT: '부활 아이템이 없다',
    NO_REVENGE_CREDIT: '오늘 무료 복수 3회를 다 썼다. 복수권이 필요하다',
    generic: '문제가 생겼다. 잠시 후 다시 시도해줘.',
  } as Record<string, string>,
};
