export const T = {
  connecting: '서버에 연결하는 중…',
  loading: '불러오는 중…',
  gold: '골드',
  soul: '영혼석',
  claimIdle: (g: number) => `방치 수입 받기 (+${g})`,
  sortie: '출정',
  introSortie: '복수하러 출정',
  resume: '진행 중인 공략이 있다',
  resumeBtn: '이어하기',
  throne: '옥좌',
  throneEmptyBadge: '성주 부재 중',
  floor: (n: number) => `${n}층`,
  emptySlot: '빈 칸',
  logTitle: '방어 기록',
  logDefended: (name: string) => `${name}의 침입을 막았다`,
  logRobbed: (name: string, g: number) => `${name}에게 털렸다 (−${g})`,
  tactics: { charge: '돌격', guard: '방진', focus: '집중' } as Record<string, string>,
  tacticHelp: { charge: '공격 +20% · 방어 −20%', guard: '방어 +30% · 속도 −1', focus: '가장 약한 적부터' } as Record<string, string>,
  ult: { knight: '방패 돌진', archer: '화살비', priest: '축복' } as Record<string, string>,
  giveUp: '포기',
  confirmGiveUp: '공략을 포기할까? 전리품은 없다.',
  revive: (n: number) => `부활 (보유 ${n})`,
  victory: '함락!',
  defeat: '전멸',
  toHome: '홈으로',
  npcTag: 'NPC',
  shadowUse: (n: number) => `그림자 대역 사용 (보유 ${n})`,
  power: '전투력',
  estLoot: '예상 약탈',
  speed: (x: number) => `${x}×`,
  throneFloor: '옥좌층',
  loot: '약탈',
  honor: '명예',
  tabs: { home: '성', upgrade: '강화', league: '리그', shop: '상점' },
  errors: {
    NO_REVIVE_CREDIT: '부활 아이템이 없다',
    generic: '문제가 생겼다. 잠시 후 다시 시도해줘.',
  } as Record<string, string>,
};
