import { formatNum as F } from '../../server/src/growth';
import type { Strings } from './ko';

/** 简体中文. 모양은 ko.ts(Strings)와 같다 */
export const zhHans: Strings = {
  connecting: '正在连接服务器…',
  loading: '加载中…',
  gold: '金币',
  soul: '魂石',
  claimIdle: (g: number) => `领取挂机收益 (+${F(g)})`,
  sortie: '出征',
  introSortie: '出征复仇',
  resume: '有进行中的攻略',
  resumeBtn: '继续',
  throne: '王座',
  floor: (n: number) => `${n}层`,
  emptySlot: '空位',
  clearSlot: '移除',
  logTitle: '防守记录',
  logDefended: (name: string) => `挡住了${name}的入侵`,
  logRobbed: (name: string, g: number) => (g > 0 ? `被${name}抢了 (−${F(g)})` : `被${name}抢了`),
  ult: { knight: '盾牌冲锋', archer: '箭雨', priest: '祝福' } as Record<string, string>,
  giveUp: '放弃',
  confirmGiveUp: '要放弃攻略吗？没有掠夺金币。',
  revive: (n: number) => `复活 (持有 ${n})`,
  victory: '攻陷！',
  defeat: '全灭',
  toHome: '回主页',
  npcTag: 'NPC',
  power: '战力',
  estLoot: '预计掠夺',
  speed: (x: number) => `${x}×`,
  throneFloor: '王座厅',
  loot: '掠夺',
  honor: '荣誉',
  tabs: { upgrade: '强化', log: '记录', league: '联赛', shop: '商店' },
  panels: { match: '要抢谁？', upgrade: '强化', log: '记录', league: '联赛', shop: '商店', settings: '设置' } as Record<string, string>,
  lockedFloor: (lv: number) => `城堡 Lv.${lv}`,
  logEmpty: '还没有人来过',
  ok: '确定',
  close: '关闭',
  editFloor: '编组',
  floorEditTitle: (n: number) => `${n}层编组`,
  save: '保存',
  cancel: '取消',
  none: '无',
  level: (n: number) => `Lv.${n}`,
  upgradeBtn: (cost: number) => `强化 (${F(cost)} 金币)`,
  maxLevel: '最高等级',
  castleLevel: (n: number) => `城堡等级 ${n}`,
  lordLevel: (n: number) => `魔王 Lv.${n}`,
  recruitSoul: (soul: number) => `招募 (魂石 ${soul})`,
  monstersTitle: '怪物',
  heroesTitle: '勇者',
  recruitTitle: '招募',
  revengeBtn: '复仇',
  raidedLive: (name: string, g: number) => `${name}抢了我的城堡 (−${F(g)})`,
  defendedLive: (name: string) => `挡住了${name}的入侵`,
  shopTitle: '商店',
  buyFor: (vx: number) => `${vx} VX`,
  purchased: '已购买',
  products: {
    starter_pack: ['新手礼包', '死灵法师 + 金币 + 魂石30'],
    recruit_dragon: ['招募幼龙', '会对全体敌人喷火的幼龙 (也能用魂石获得)'],
    season_pass: ['赛季通行证', '赛季奖励的通行证奖励列 + 限定魔王外观'],
    speed_x3: ['3倍速', '攻略与攻城快3倍 (永久)'],
    premium: ['高级通行证', '不看广告直接领奖励 (每日上限相同，永久)'],
  } as Record<string, [string, string]>,
  buyStarter: '查看新手礼包',
  starterDesc: (gold: number) => `死灵法师 + 金币 ${F(gold)} + 魂石30`,
  leagueTitle: (id: string) => `第 ${id.slice(1)} 赛季`,
  endsIn: (ms: number) => `距离结束 ${Math.max(0, Math.floor(ms / 86_400_000))}天 ${Math.max(0, Math.floor((ms % 86_400_000) / 3_600_000))}小时`,
  myHonor: (h: number) => `我的荣誉 ${h}`,
  bracketTitle: '我的分组 (30人)',
  seasonReward: (a: number, b: number, c: number, d: number) => `赛季结束奖励 (分组排名): 第1名 魂石${a} · 第2〜3名 ${b} · 第4〜10名 ${c} · 其他 ${d}`,
  honorHow: '荣誉: 攻略胜利 10 · 击败魔王 +5 · 复仇 2倍 · 防守成功 3',
  topTitle: '全服前20名',
  noBracket: '赢得第一次攻略就会加入分组',
  stats: { hp: '体力', atk: '攻击', def: '防御', spd: '速度' },
  skills: {
    taunt: (cd: number) => `嘲讽: 每${cd}回合，吸引敌人攻击2回合`,
    pierce: (cd: number) => `贯穿: 每${cd}回合，无视一半防御斩击`,
    backline: () => '奇袭 (常驻): 优先攻击后排敌人',
    web: (cd: number) => `蛛网: 每${cd}回合，使一名敌人减速2回合`,
    raise: () => '复苏 (常驻): 让第一个倒下的队友以30%体力复活一次',
    breath: (cd: number) => `火焰: 每${cd}回合，灼烧全体敌人 (60%)`,
    double_shot: (cd: number) => `连射: 每${cd}回合，射击两次 (各60%)`,
    heal: (cd: number) => `治愈: 每${cd}回合，为伤势最重的队友恢复25%体力`,
    dark_wave: (cd: number) => `暗黑波动: 每${cd}回合，攻击全体敌人 (80%)`,
  } as Record<string, (cd: number) => string>,
  tut: {
    raidSortie: '先从隔壁公会的城堡开始抢吧！',
    raidUlt: '气攒满后，必杀技会自动发动。请欣赏！',
    raidResult: '金币到手了！',
    placeFloor: '现在也得守住我们的城堡。请点1层。',
    placeSlot: '在空位上安排手下。',
    upgradeTab: '用金币让手下变强！',
    upgradeOne: '强化一次看看吧。',
    matchSortie: '这次是真正别人的城堡。出征！',
    end: '接下来就交给您了，魔王大人。(点击开始)',
  },
  cutscene: {
    skip: '跳过',
    lines: [
      '小恶魔：“魔王大人，城堡的维修费已经拖欠三个月了。”',
      '小恶魔：“隔壁的魔王城金币多得溢出来…可惜勇者们天天去抢。”',
      '魔王：“…那我也去当勇者就行了。”',
      '魔王：“白天当勇者去抢别人的城堡，”',
      '魔王：“晚上当魔王守住自己的城堡。”',
    ],
    title: '白天是勇者，晚上是魔王',
  },
  nick: {
    title: '魔王的名字',
    hint: '2〜8个字，韩文・英文・数字',
    placeholder: '名字',
    submit: '就决定是这个',
  },
  settings: {
    title: '设置',
    bgm: '背景音乐',
    sfx: '音效',
    on: '开启',
    off: '关闭',
    nickname: '昵称',
    renameLeft: (n: number) => `免费修改剩余${n}次`,
    rename: '修改',
    reset: '重置数据',
    resetWarn: '城堡、等级、金币、魂石、记录与本赛季的荣誉都会回到最初。付费获得的怪物、挂机2倍、赛季通行证、剩余道具、昵称与攻城最高记录会保留。会重新进行教程。无法恢复。',
    resetType: '请输入“重置”以确认',
    resetWord: '重置',
    resetGo: '重置',
    resetDone: '已重置',
    lordLook: '魔王外观',
    looks: { base: '基本', skull: '骷髅君主', dragon: '黑龙' } as Record<string, string>,
  },
  pass: {
    rank: '排名',
    track: '通行证',
    tier: (n: number) => `第${n}阶`,
    done: '完成',
    prev: '上一页',
    next: '下一页',
    dragon: '黑龙',
    passOnly: '通行证',
    claimAll: '全部领取',
    got: (gold: number, soul: number, skin: boolean) =>
      `已领取！ ${[gold ? `金币 ${F(gold)}` : '', soul ? `魂石 ${soul}` : '', skin ? '黑龙外观' : ''].filter(Boolean).join(' · ')}`,
  },
  away: {
    title: '离开的这段时间',
    waves: (n: number, held: number) => `入侵 ${n}次 · 挡住 ${held}次`,
    stage: (from: number, to: number) => `攻城 第${from}阶 → 第${to}阶`,
    gold: (g: number) => `累积金币 +${F(g)}`,
    later: '稍后',
  },
  siege: {
    stage: (n: number) => `攻城 第${n}阶`,
    next: (n: number, ms: number) => `攻城 第${n}阶 · ${Math.floor(ms / 60_000)}:${String(Math.floor(ms / 1000) % 60).padStart(2, '0')}`,
    breached: '王座失守！阶段下降',
    call: '立即召唤',
    rankTab: '攻城',
    best: (n: number) => `最高 ${n}`,
    myBest: (n: number) => `我的最高 第${n}阶`,
    milestoneHint: '每10阶首次突破可得魂石',
    noRank: '还没有记录',
    rankFailed: '无法加载排名',
    milestone: (soul: number) => `攻城阶段首次突破！魂石 +${soul}`,
    power: '战力',
    heroHint: '攻略时出战的我方队伍。越强越容易抢下别人的城堡',
    heroBonus: (p: number) => `当前 掠夺金币 +${p}% · 攻城防守 +${p}%`,
    heroNext: (p: number) => `强化后 掠夺金币・攻城防守 +${p}% → +${p + 1}%`,
  },
  ads: {
    watch: (label: string) => `${label} (广告)`,
    instant: (label: string) => `${label} (立即)`,
    dismissed: '看完广告才能领取',
    failed: '现在无法观看广告，请稍后再试',
    left: (n: number) => `今天剩${n}次`,
    tomorrow: '明天再来',
    supply: '每日补给',
    supplyDesc: (gold: number, soul: number) => `金币 ${F(gold)} + 魂石 ${soul}`,
    receive: '领取',
    revenge: '复仇 +1',
    revive: '复活',
    plain: (g: number) => `直接领取 +${F(g)}`,
    double: (mult: number, g: number) => `${mult}倍领取 +${F(g)}`,
    got: '已领取！',
  },
  errors: {
    AD_PLACEMENT: '请再试一次',
    AD_LIMIT: '今天已经全部领完了',
    AD_NOT_NOW: '现在无法领取',
    AD_NOT_VERIFIED: '无法确认广告，请再试一次',
    AD_USED: '这个广告奖励已经领过了',
    NICK_LENGTH: '名字请用2〜8个字',
    NICK_CHARS: '只能使用韩文、英文与数字',
    NICK_JAMO: '不能只用ㄱ、ㅏ这类单独字母，请输入完整的韩文字',
    NICK_BANNED: '这个名字不能使用',
    NICK_TAKEN: '这个名字已经有人用了',
    NICK_NO_CHANGES: '免费修改已经用过了',
    SKIN_NOT_OWNED: '没有这个外观',
    SIEGE_TOO_SOON: '下一波前20秒内才能召唤',
    NO_SPEED3: '3倍速是商店商品',
    PASS_NOTHING: '没有可领取的奖励',
    RESET_CONFIRM: '请正确输入“重置”',
    RESET_IN_RAID: '攻略中无法重置',
    ONBOARDING_ORDER: '请再试一次',
    NO_REVIVE_CREDIT: '没有复活道具',
    NO_REVENGE_CREDIT: '今天3次免费复仇已用完，需要复仇券',
    generic: '出了点问题，请稍后再试。',
  } as Record<string, string>,
  serverMsg: {
    '골드가 부족하다': '金币不足',
    '영혼석이 부족하다': '魂石不足',
    '최대 레벨이다': '已经是最高等级',
    '성이 최대 레벨이다': '城堡已是最高等级',
    '이미 공략 중이다': '已经在攻略中',
    '공략 중에는 편성을 바꿀 수 없다': '攻略中无法修改编组',
    '복수 기한(24시간)이 지났다': '已超过复仇期限 (24小时)',
    '복수할 수 없는 기록이다': '这条记录无法复仇',
    '부활은 판당 1회다': '每场攻略只能复活1次',
    '이미 보유한 몬스터다': '已经拥有这只怪物',
    '다시 시도해줘': '请再试一次',
  } as Record<string, string>,
  units: {
    slime: '史莱姆', skeleton: '骷髅兵', imp: '小恶魔', spider: '蜘蛛', necro: '死灵法师', dragon: '幼龙',
    knight: '骑士', archer: '弓箭手', priest: '圣职者', lord: '魔王',
  } as Record<string, string>,
  fx: { taunt: '嘲讽', web: '蛛网', stun: '眩晕', down: '倒下', raise: '化为亡灵复活', cleared: '突破楼层' } as Record<string, string>,
  names: {
    guild: '入侵者公会',
    guildApprentice: '入侵者公会 见习',
    guildRookie: '入侵者公会 新人',
    guildTier: (n: number) => `入侵者公会 ${n}段`,
    ghost: (n: number) => `暗影魔王 ${n}`,
    lordTag: (tag: string) => `魔王 #${tag}`,
  },
  load: {
    top: '白天是勇者，',
    main: '晚上是魔王',
    connect: '正在连接服务器…',
    home: '正在加载城堡…',
    assets: '正在打开城门…',
    tips: [
      '提示: 离开时攻城也会继续',
      '提示: 复仇可得2倍荣誉',
      '提示: 每强化一次勇者 掠夺金币 +1%',
      '提示: 攻城每10阶首次突破可得魂石',
    ],
  },
  lang: { title: '语言', pick: '请选择语言', go: '开始' },
};
