import { formatNum as F } from '../../server/src/growth';
import type { Strings } from './ko';

/** 繁體中文. 모양은 ko.ts(Strings)와 같다 */
export const zhHant: Strings = {
  connecting: '正在連線到伺服器…',
  loading: '載入中…',
  gold: '金幣',
  soul: '魂石',
  idleBtn: '掛機獎勵',
  claimIdle: (g: number) => `領取放置收益 (+${F(g)})`,
  sortie: '出征',
  introSortie: '出征復仇',
  resume: '有進行中的攻略',
  resumeBtn: '繼續',
  throne: '王座',
  floor: (n: number) => `${n}樓`,
  emptySlot: '空位',
  clearSlot: '移除',
  logTitle: '防守紀錄',
  logDefended: (name: string) => `擋下了${name}的入侵`,
  logRobbed: (name: string, g: number) => (g > 0 ? `被${name}搶了 (−${F(g)})` : `被${name}搶了`),
  ult: { knight: '盾牌衝鋒', archer: '箭雨', priest: '祝福' } as Record<string, string>,
  giveUp: '放棄',
  confirmGiveUp: '要放棄攻略嗎？沒有掠奪金幣。',
  revive: (n: number) => `復活 (持有 ${n})`,
  victory: '攻陷！',
  defeat: '全滅',
  toHome: '回主頁',
  npcTag: 'NPC',
  power: '戰力',
  estLoot: '預計掠奪',
  speed: (x: number) => `${x}×`,
  throneFloor: '王座廳',
  loot: '掠奪',
  honor: '榮譽',
  tabs: { upgrade: '強化', log: '紀錄', league: '聯賽', shop: '商店' },
  panels: { match: '要搶誰？', upgrade: '強化', log: '紀錄', league: '聯賽', shop: '商店', settings: '設定' } as Record<string, string>,
  lockedFloor: (lv: number) => `城堡 Lv.${lv}`,
  logEmpty: '還沒有人來過',
  ok: '確認',
  close: '關閉',
  editFloor: '編組',
  floorEditTitle: (n: number) => `${n}樓編組`,
  save: '儲存',
  cancel: '取消',
  none: '無',
  level: (n: number) => `Lv.${n}`,
  upgradeBtn: (cost: number) => `強化 (${F(cost)} 金幣)`,
  maxLevel: '最高等級',
  castleLevel: (n: number) => `城堡等級 ${n}`,
  lordLevel: (n: number) => `魔王 Lv.${n}`,
  recruitSoul: (soul: number) => `招募 (魂石 ${soul})`,
  monstersTitle: '怪物',
  heroesTitle: '勇者',
  recruitTitle: '招募',
  revengeBtn: '復仇',
  raidedLive: (name: string, g: number) => `${name}搶了我的城堡 (−${F(g)})`,
  defendedLive: (name: string) => `擋下了${name}的入侵`,
  shopTitle: '商店',
  buyFor: (vx: number) => `${vx} VX`,
  purchased: '已購買',
  products: {
    starter_pack: ['新手禮包', '死靈法師 + 金幣 + 魂石30'],
    season_pass: ['賽季通行證', '賽季獎勵的通行證獎勵列 + 限定魔王外觀'],
    speed_x3: ['3倍速', '攻略與攻城快3倍 (永久)'],
    premium: ['高級通行證', '不看廣告直接領獎勵 (每日上限相同，永久)'],
    gold_pouch: ['金幣袋', '金幣'],
    gold_chest: ['金幣箱', '金幣'],
    gold_coffer: ['黃金寶箱', '金幣'],
    gold_vault: ['魔王寶庫', '金幣'],
    soul_pouch: ['魂石小袋', '魂石'],
    soul_sack: ['魂石大袋', '魂石'],
    soul_chest: ['魂石寶箱', '魂石'],
    soul_altar: ['魂石祭壇', '魂石'],
    soul_relic: ['魂石聖遺物', '魂石'],
  } as Record<string, [string, string]>,
  goldPackDesc: (gold: number, bonus: number) => (bonus > 0 ? `金幣 ${F(gold)} · 多送${bonus}%` : `金幣 ${F(gold)}`),
  soulPackDesc: (soul: number, bonus: number) => (bonus > 0 ? `魂石 ${F(soul)} · 多送${bonus}%` : `魂石 ${F(soul)}`),
  sortieInfo: (left: number, total: number, lord: number, lordCap: number) => `今日出征 ${left}/${total} · 擊敗魔王魂石 ${lord}/${lordCap}`,
  buyTicket: (gold: number) => `購買出征券（${F(gold)} 金幣）`,
  goldForSoul: (soul: number) => `魂石 ${F(soul)}`,
  gainGold: (n: number) => `金幣 +${F(n)}`,
  gainSoul: (n: number) => `魂石 +${F(n)}`,
  buyStarter: '查看新手禮包',
  starterDesc: (gold: number) => `死靈法師 + 金幣 ${F(gold)} + 魂石30`,
  leagueTitle: (id: string) => `第 ${id.slice(1)} 賽季`,
  endsIn: (ms: number) => `距離結束 ${Math.max(0, Math.floor(ms / 86_400_000))}天 ${Math.max(0, Math.floor((ms % 86_400_000) / 3_600_000))}小時`,
  myHonor: (h: number) => `我的榮譽 ${h}`,
  bracketTitle: '我的分組 (30人)',
  seasonReward: (a: number, b: number, c: number, d: number) => `賽季結束獎勵 (分組排名): 第1名 魂石${a} · 第2〜3名 ${b} · 第4〜10名 ${c} · 其他 ${d}`,
  honorHow: '榮譽: 攻略勝利 10 · 擊敗魔王 +5 · 復仇 2倍 · 防守成功 3',
  topTitle: '全服前20名',
  globalReward: '全服排名獎勵：第1名 稱號「霸王」・名人堂 · 第2~3名 稱號・名人堂 · 第4~10名 稱號（下個賽季期間）',
  hallTitle: '名人堂',
  hallSeason: (id: string) => `賽季 ${id.slice(1)}`,
  titles: { champion: '霸王', top3: '前3強', top10: '前10強' } as Record<string, string>,
  noBracket: '贏得第一次攻略就會加入分組',
  stats: { hp: '體力', atk: '攻擊', def: '防禦', spd: '速度' },
  skills: {
    taunt: (cd: number) => `嘲諷: 每${cd}回合，吸引敵人攻擊2回合`,
    pierce: (cd: number) => `貫穿: 每${cd}回合，無視一半防禦斬擊`,
    backline: () => '奇襲 (常駐): 優先攻擊後排敵人',
    web: (cd: number) => `蛛網: 每${cd}回合，使一名敵人減速2回合`,
    raise: () => '復甦 (常駐): 讓第一個倒下的隊友以30%體力復活一次',
    breath: (cd: number) => `火焰: 每${cd}回合，燒灼全體敵人 (60%)`,
    thorns: () => '尖刺岩（常駐）: 受到攻擊時，把所受傷害的30%反彈給攻擊者',
    scream: (cd: number) => `尖嘯: 每${cd}回合，使一名敵人暈眩1回合`,
    lifesteal: () => '吸血（常駐）: 回復造成傷害的30%',
    execute: (cd: number) => `處決: 每${cd}回合，對體力最低的敵人造成2倍傷害`,
    double_shot: (cd: number) => `連射: 每${cd}回合，射擊兩次 (各60%)`,
    heal: (cd: number) => `治癒: 每${cd}回合，為傷勢最重的隊友恢復25%體力`,
    dark_wave: (cd: number) => `暗黑波動: 每${cd}回合，攻擊全體敵人 (80%)`,
  } as Record<string, (cd: number) => string>,
  tut: {
    raidSortie: '先從隔壁公會的城堡開始搶吧！',
    raidUlt: '氣集滿後，必殺技會自動發動。請欣賞！',
    raidResult: '金幣到手了！',
    placeFloor: '現在也得守住我們的城堡。請按1樓。',
    placeSlot: '在空位上安排手下。',
    upgradeTab: '用金幣讓手下變強！',
    upgradeOne: '強化一次看看吧。',
    matchSortie: '這次是真正別人的城堡。出征！',
    end: '接下來就交給您了，魔王大人。(按一下開始)',
  },
  cutscene: {
    skip: '跳過',
    lines: [
      '小惡魔：「魔王大人，城堡的維修費已經拖欠三個月了。」',
      '小惡魔：「隔壁的魔王城金幣多得滿出來…只可惜勇者們天天去搶。」',
      '魔王：「…那我也去當勇者就行了。」',
      '魔王：「白天當勇者去搶別人的城堡，」',
      '魔王：「晚上當魔王守住自己的城堡。」',
    ],
    title: '白天是勇者，晚上是魔王',
  },
  nick: {
    title: '魔王的名字',
    hint: '2〜8個字，韓文・英文・數字',
    placeholder: '名字',
    submit: '就決定是這個',
  },
  settings: {
    title: '設定',
    bgm: '背景音樂',
    sfx: '音效',
    on: '開啟',
    off: '關閉',
    nickname: '暱稱',
    renameLeft: (n: number) => `免費更改剩餘${n}次`,
    rename: '更改',
    reset: '重置資料',
    resetWarn: '城堡、等級、金幣、紀錄與本賽季的榮譽都會回到最初。魂石、覺醒星數、付費取得的怪物、放置2倍、賽季通行證、剩餘道具、暱稱與攻城最高紀錄會保留。會重新進行教學。無法復原。',
    resetType: '請輸入「重置」以確認',
    resetWord: '重置',
    resetGo: '重置',
    resetDone: '已重置',
    lordLook: '魔王外觀',
    looks: { base: '基本', skull: '骷髏君主', dragon: '黑龍', lava: '熔岩魔王', demon: '紫翼惡魔', summon1: '墮落大惡魔' } as Record<string, string>,
  },
  pass: {
    rank: '排名',
    track: '通行證',
    tier: (n: number) => `第${n}階`,
    done: '完成',
    prev: '上一頁',
    next: '下一頁',
    dragon: '黑龍',
    passOnly: '通行證',
    claimAll: '全部領取',
    got: (gold: number, soul: number, skin: boolean) =>
      `已領取！ ${[gold ? `金幣 ${F(gold)}` : '', soul ? `魂石 ${soul}` : '', skin ? '黑龍外觀' : ''].filter(Boolean).join(' · ')}`,
  },
  away: {
    title: '離開的這段時間',
    waves: (n: number, held: number) => `入侵 ${n}次 · 擋下 ${held}次`,
    stage: (from: number, to: number) => `攻城 第${from}階 → 第${to}階`,
    gold: (g: number) => `累積金幣 +${F(g)}`,
    later: '稍後',
  },
  siege: {
    stage: (n: number) => `攻城 第${n}階`,
    next: (n: number, ms: number) => `攻城 第${n}階 · ${Math.floor(ms / 60_000)}:${String(Math.floor(ms / 1000) % 60).padStart(2, '0')}`,
    breached: '王座失守！階段下降',
    call: '立刻召喚',
    rankTab: '攻城',
    best: (n: number) => `最高 ${n}`,
    myBest: (n: number) => `我的最高 第${n}階`,
    milestoneHint: '每刷新一次最高階段得魂石10，每10階段再加',
    noRank: '還沒有紀錄',
    rankFailed: '無法載入排名',
    milestone: (soul: number) => `攻城階段首次突破！魂石 +${soul}`,
    power: '戰力',
    heroHint: '攻略時出戰的我方隊伍。越強越容易搶下別人的城堡',
    heroBonus: (p: number) => `目前 掠奪金幣 +${p}% · 攻城防守 +${p}%`,
    heroNext: (p: number) => `強化後 掠奪金幣・攻城防守 +${p}% → +${p + 1}%`,
  },
  ads: {
    watch: (label: string) => `${label} (廣告)`,
    instant: (label: string) => `${label} (立即)`,
    dismissed: '看完廣告才能領取',
    failed: '現在無法觀看廣告，請稍後再試',
    left: (n: number) => `今天剩${n}次`,
    tomorrow: '明天再來',
    supply: '每日補給',
    supplyDesc: (gold: number, soul: number) => `金幣 ${F(gold)} + 魂石 ${soul}`,
    receive: '領取',
    revenge: '復仇 +1',
    revive: '復活',
    plain: (g: number) => `直接領取 +${F(g)}`,
    double: (mult: number, g: number) => `${mult}倍領取 +${F(g)}`,
    got: '已領取！',
  },
  errors: {
    AD_PLACEMENT: '請再試一次',
    AD_LIMIT: '今天已經全部領完了',
    AD_NOT_NOW: '現在無法領取',
    AD_NOT_VERIFIED: '無法確認廣告，請再試一次',
    AD_USED: '這個廣告獎勵已經領過了',
    NICK_LENGTH: '名字請用2〜8個字',
    NICK_CHARS: '只能使用韓文、英文與數字',
    NICK_JAMO: '不能只用ㄱ、ㅏ這類單獨字母，請輸入完整的韓文字',
    NICK_BANNED: '這個名字不能使用',
    NICK_TAKEN: '這個名字已經有人用了',
    NICK_NO_CHANGES: '免費更改已經用過了',
    SKIN_NOT_OWNED: '沒有這個外觀',
    SIEGE_TOO_SOON: '下一波前20秒內才能召喚',
    NO_SPEED3: '3倍速是商店商品',
    PASS_NOTHING: '沒有可領取的獎勵',
    RESET_CONFIRM: '請正確輸入「重置」',
    RESET_IN_RAID: '攻略中無法重置',
    ONBOARDING_ORDER: '請再試一次',
    NO_REVIVE_CREDIT: '沒有復活道具',
    NO_REVENGE_CREDIT: '今天3次免費復仇已用完，需要復仇券',
    NO_SORTIE: '今天的出征券已用完，可用金幣購買',
    NO_SOUL: '魂石不足',
    MAX_STARS: '已經完全覺醒',
    generic: '發生問題，請稍後再試。',
  } as Record<string, string>,
  serverMsg: {
    '골드가 부족하다': '金幣不足',
    '영혼석이 부족하다': '魂石不足',
    '최대 레벨이다': '已經是最高等級',
    '성이 최대 레벨이다': '城堡已是最高等級',
    '이미 공략 중이다': '已經在攻略中',
    '공략 중에는 편성을 바꿀 수 없다': '攻略中無法更改編組',
    '복수 기한(24시간)이 지났다': '已超過復仇期限 (24小時)',
    '복수할 수 없는 기록이다': '這筆紀錄無法復仇',
    '부활은 판당 1회다': '每場攻略只能復活1次',
    '이미 보유한 몬스터다': '已經擁有這隻怪物',
    '다시 시도해줘': '請再試一次',
  } as Record<string, string>,
  units: {
    slime: '史萊姆', skeleton: '骷髏兵', imp: '小惡魔', spider: '蜘蛛', necro: '死靈法師', dragon: '幼龍', golem: '岩石魔像', banshee: '女妖', vampire: '吸血鬼', deathknight: '死亡騎士',
    knight: '騎士', archer: '弓箭手', priest: '聖職者', lord: '魔王',
  } as Record<string, string>,
  fx: { taunt: '嘲諷', web: '蛛網', stun: '暈眩', down: '倒下', raise: '化為亡靈復活', cleared: '突破樓層' } as Record<string, string>,
  names: {
    guild: '入侵者公會',
    guildApprentice: '入侵者公會 見習',
    guildRookie: '入侵者公會 新人',
    guildTier: (n: number) => `入侵者公會 ${n}段`,
    ghost: (n: number) => `暗影魔王 ${n}`,
    lordTag: (tag: string) => `魔王 #${tag}`,
  },
  load: {
    top: '白天是勇者，',
    main: '晚上是魔王',
    connect: '正在連線到伺服器…',
    home: '正在載入城堡…',
    assets: '正在打開城門…',
    tips: [
      '提示: 離開時攻城也會繼續',
      '提示: 復仇可得2倍榮譽',
      '提示: 每強化一次勇者 掠奪金幣 +1%',
      '提示: 每刷新一次攻城最高階段就能獲得魂石',
    ],
  },
  vip: {
    level: (n: number) => `VIP ${n}`,
    none: '非VIP',
    toNext: (vx: number, n: number) => `距離 VIP ${n} 還差 ${vx.toLocaleString()} VX`,
    max: '最高等級',
    nextTitle: '下一等級福利',
    idle: (p: number) => `放置收益 +${p}%`,
    away: (m: number) => `離開時攻城金幣 ×${m}`,
    cap: (h: number) => `放置上限 ${h}小時`,
    pack: (p: number) => `金幣禮包 +${p}%`,
    idleAd: (n: number) => `廣告1.5倍 每天${n}次`,
    revenge: (n: number) => `免費復仇 每天${n}次`,
    nickname: '暱稱免費更改 +1',
    skin: (name: string) => `專屬外觀: ${name}`,
    aura: '紅寶石光環',
    skins: { lava: '熔岩魔王', demon: '紫翼惡魔' } as Record<string, string>,
  },
  awaken: {
    upTab: '強化',
    tab: '覺醒',
    hint: '每顆星讓全部能力×1.1。消耗魂石，重置後仍保留。',
    btn: (soul: number) => `覺醒（魂石 ${F(soul)}）`,
    max: '已完全覺醒',
    mult: (now: string, next: string | null) => (next ? `能力 ×${now} → ×${next}` : `能力 ×${now}`),
    buySoul: '購買魂石',
  },
  news: {
    vip10: (name: string) => `${name} 達到 VIP 10！`,
    star20: (name: string) => `${name} 完成了20星覺醒！`,
    champion: (name: string) => `${name} 拿下上賽季全服第1名，成為「霸王」！`,
  } as Record<string, (name: string) => string>,
  summon: {
    open: '召喚',
    pity: (n: number) => `距離英雄以上還有${n}次`,
    rates: '機率',
    one: '1次',
    ten: '10+1次',
    result: '召喚結果',
    ok: '確定',
    skip: '全部顯示',
    fresh: 'NEW',
    look: (name: string) => `外觀: ${name}`,
    baseLook: '基本',
    wearWhere: '獲得的外觀在強化畫面的怪物欄穿上',
    ratesTitle: '召喚機率',
    grades: { common: '普通', rare: '稀有', epic: '英雄', legend: '傳說' },
    rewardOf: { common: '魂石 15', rare: '魂石 50', epic: '12種怪物裝備外觀之一', legend: '召喚限定魔王外觀' },
    tenNote: '10+1次必得一個英雄以上。',
    pityNote: (n: number) => `連續沒有英雄以上時，第${n}次召喚必得英雄以上；抽到後重新計算。`,
    dupNote: (epic: number, legend: number) => `抽到已有的外觀會換成魂石(英雄${epic}、傳說${F(legend)})。`,
    gear: {
      'slime:crown': '史萊姆王', 'slime:helm': '騎士史萊姆', 'skeleton:royal': '骷髏王', 'skeleton:dread': '恐懼之鎧',
      'imp:king': '小惡魔王', 'imp:warlock': '黑巫師小惡魔', 'necro:lich': '巫妖王', 'necro:bone': '骨甲',
      'spider:iron': '鋼鐵蜘蛛', 'spider:crown': '蜘蛛女王', 'dragon:knight': '騎士龍', 'dragon:royal': '王室之龍',
    } as Record<string, string>,
  },
  lang: { title: '語言', pick: '請選擇語言', go: '開始' },
};
