import { formatNum as F } from '../../server/src/growth';
import type { Strings } from './ko';

/** 简体中文. 모양은 ko.ts(Strings)와 같다 */
export const zhHans: Strings = {
  connecting: '正在连接服务器…',
  loading: '加载中…',
  gold: '金币',
  soul: '魂石',
  icons: { shop: '商店', rank: '排名', rankN: (n: number) => `第${n}名`, log: '记录' },
  upMany: { ten: '×10', max: (n: number) => `最大 +${n}` },
  quest: {
    title: '委托', next: '下一步', go: '前往', claim: '领取', done: '完成', after: '之后', all: '全部完成',
    siegeWait: '波次在主页等待就会上升',
    tabs: { guide: '成长', daily: '每日' },
    guide: {
      unit: (name: string, n: number) => `${name}强化到Lv.${n}`,
      anyLevel: (n: number) => `任一怪物Lv.${n}`,
      wins: (n: number) => `攻略胜利${n}次`,
      castle: (n: number) => `城堡Lv.${n}`,
      filled: (n: number) => `放置${n}格怪物`,
      idle: '领取挂机奖励',
      summon: (n: number) => `召唤${n}次`,
      siege: (n: number) => `第${n}波`,
      stars: (n: number) => `觉醒星${n}颗`,
    },
    daily: {
      sortie: (n: number) => `出征${n}次`,
      win: (n: number) => `攻略胜利${n}次`,
      upgrade: (n: number) => `强化${n}次`,
      idle: () => '领取挂机奖励',
    },
  },
  up: {
    one: '×1', ten: '×10', max: '最大',
    nextFloor: (n: number) => `下一级: 开放第${n}层`,
    nextUnit: (name: string) => `下一级: ${name}加入`,
    nextLord: '下一级: 魔王变强',
    lordShort: '每颗星×1.1',
    heroBonus: (p: number) => `掠夺·防御 +${p}%`,
    awaken: '觉醒', recruit: '招募', maxLv: '最大',
    nextLevel: '下一级',
    info: '说明',
  },
  castleHint: '增加栏位与楼层，魔王变强',
  diff: { easy: '简单', normal: '普通', hard: '困难' } as Record<'easy' | 'normal' | 'hard', string>,
  again: '再次出征',
  rec: '推荐',
  unlocks: { heroes: '新解锁：勇者 — 出征时攻打其他城堡的我方队伍', summon: '新解锁：召唤 — 用魂石抽取怪物装备外观', awaken: '新解锁：觉醒 — 到50级后加星变得更强' } as Record<string, string>,
  heroIntro: '勇者 = 出征时攻打其他城堡的我方队伍 · 升级还会提高城堡防御',
  heroRole: { knight: '在前方承受敌人的攻击', archer: '从后方射箭(偶尔连射两次)', priest: '治疗受伤的队友' } as Record<string, string>,
  spend: { title: '赛季累计消费', claim: '领取', done: '全部达成', look: '限定外观', got: (name: string) => `获得新外观「${name}」！` },
  shop: { valuePct: (p: number) => `效率${p}%`, firstX2: '首购双倍', title: '魔王宝库', once: '限购一次', season: '本赛季', best: 'BEST', tabs: { soul: '魂石', gold: '金币', special: '特别' } as Record<'soul' | 'gold' | 'special', string> },
  idleBtn: '挂机奖励',
  claimIdle: (g: number) => `领取挂机收益 (+${F(g)})`,
  sortie: '出征',
  introSortie: '出征复仇',
  resume: '有进行中的攻略',
  resumeBtn: '继续',
  throne: '王座',
  floor: (n: number) => `${n}层`,
  emptySlot: '空位',
  clearSlot: '移除',
  pickHint: '拥有的怪物 — 点击放到 ▼ 位置',
  placedAt: (n: number) => `${n}层`,
  logTitle: '防守记录',
  logDefended: (name: string) => `挡住了${name}的入侵`,
  logRobbed: (name: string, g: number) => (g > 0 ? `被${name}抢了 (−${F(g)})` : `被${name}抢了`),
  ult: { knight: '盾牌冲锋', archer: '箭雨', priest: '祝福' } as Record<string, string>,
  giveUp: '放弃',
  confirmGiveUp: '要放弃攻略吗？没有掠夺金币。',
  revive: (n: number) => `复活 (持有 ${n})`,
  victory: '攻陷！',
  defeat: '全灭',
  toHome: '回主页',
  npcTag: 'NPC',
  power: '战力',
  estLoot: '预计掠夺',
  speed: (x: number) => `${x}×`,
  throneFloor: '王座厅',
  loot: '掠夺',
  honor: '荣誉',
  tabs: { upgrade: '强化', log: '记录', league: '联赛', shop: '商店' },
  panels: { match: '要抢谁？', upgrade: '强化', log: '记录', league: '联赛', shop: '商店', settings: '设置' } as Record<string, string>,
  lockedFloor: (lv: number) => `城堡 Lv.${lv} 开放`,
  logEmpty: '还没有人来过',
  ok: '确定',
  close: '关闭',
  editFloor: '编组',
  floorEditTitle: (n: number) => `${n}层编组`,
  save: '保存',
  cancel: '取消',
  none: '无',
  level: (n: number) => `Lv.${n}`,
  upgradeBtn: (cost: number) => `强化 (${F(cost)} 金币)`,
  maxLevel: '最高等级',
  castleLevel: (n: number) => `城堡等级 ${n}`,
  lordLevel: (n: number) => `魔王 Lv.${n}`,
  recruitSoul: (soul: number) => `招募 (魂石 ${soul})`,
  monstersTitle: '怪物',
  heroesTitle: '勇者',
  recruitTitle: '招募怪物',
  revengeBtn: '复仇',
  raidedLive: (name: string, g: number) => `${name}抢了我的城堡 (−${F(g)})`,
  defendedLive: (name: string) => `挡住了${name}的入侵`,
  shopTitle: '商店',
  buyFor: (vx: number) => `${vx} VX`,
  purchased: '已购买',
  products: {
    starter_pack: ['新手礼包', '死灵法师 + 金币 + 魂石30'],
    season_pass: ['赛季通行证', '赛季奖励的通行证奖励列 + 10阶黑龙外观（永久，魔王 +10%）'],
    speed_x3: ['3倍速', '攻略与波次快3倍 (永久)'],
    premium: ['高级通行证', '免广告领奖励 + 攻略·波次3倍速 + 魂石360 (永久)'],
    gold_pouch: ['金币袋', '金币'],
    gold_chest: ['金币箱', '金币'],
    gold_coffer: ['黄金宝箱', '金币'],
    gold_vault: ['魔王宝库', '金币'],
    soul_pouch: ['魂石小袋', '魂石'],
    soul_sack: ['魂石大袋', '魂石'],
    soul_chest: ['魂石宝箱', '魂石'],
    soul_altar: ['魂石祭坛', '魂石'],
    soul_relic: ['魂石圣遗物', '魂石'],
  } as Record<string, [string, string]>,
  goldPackDesc: (gold: number, bonus: number) => (bonus > 0 ? `金币 ${F(gold)} · 多送${bonus}%` : `金币 ${F(gold)}`),
  soulPackDesc: (soul: number, bonus: number) => (bonus > 0 ? `魂石 ${F(soul)} · 多送${bonus}%` : `魂石 ${F(soul)}`),
  sortieInfo: (left: number, total: number, lord: number, lordCap: number) => `出征券 ${left}/${total}（每10分钟1张）· 今日击败魔王魂石 ${lord}/${lordCap}`,
  buyTicket: (gold: number) => `购买出征券（${F(gold)} 金币）`,
  goldForSoul: (soul: number) => `魂石 ${F(soul)}`,
  gainGold: (n: number) => `金币 +${F(n)}`,
  gainSoul: (n: number) => `魂石 +${F(n)}`,
  buyStarter: '查看新手礼包',
  starterDesc: (gold: number) => `死灵法师 + 金币 ${F(gold)} + 魂石30`,
  leagueTitle: (id: string) => `第 ${id.slice(1)} 赛季`,
  endsIn: (ms: number) => `距离结束 ${Math.max(0, Math.floor(ms / 86_400_000))}天 ${Math.max(0, Math.floor((ms % 86_400_000) / 3_600_000))}小时`,
  myHonor: (h: number) => `我的荣誉 ${h}`,
  bracketTitle: '同组排名 (最多30人)',
  seasonReward: (a: number, b: number, c: number, d: number) => `赛季结束奖励 (分组排名): 第1名 魂石${a} · 第2〜3名 ${b} · 第4〜10名 ${c} · 其他 ${d}`,
  honorHow: '荣誉: 攻略胜利 10 · 击败魔王 +5 · 复仇 2倍 · 防守成功 3',
  topTitle: '全服前20名',
  globalReward: '全服排名奖励：第1名 称号「霸王」・名人堂 · 第2~3名 称号・名人堂 · 第4~10名 称号（下个赛季期间）',
  hallTitle: '名人堂',
  hallSeason: (id: string) => `赛季 ${id.slice(1)}`,
  titles: { champion: '霸王', top3: '前3强', top10: '前10强' } as Record<string, string>,
  noBracket: '赢得第一次攻略就会加入分组',
  matchIntro: '出征：抢夺其他城堡带回金币。根据战力和难度选择。',
  stats: { hp: '体力', atk: '攻击', def: '防御', spd: '速度' },
  skills: {
    taunt: (cd: number) => `嘲讽: 每攻击${cd}次，吸引敌人攻击2秒`,
    pierce: (cd: number) => `贯穿: 每攻击${cd}次，无视一半防御斩击`,
    backline: () => '奇袭 (常驻): 优先攻击后排敌人',
    web: (cd: number) => `蛛网: 每攻击${cd}次，使一名敌人减速2秒`,
    raise: () => '复苏 (常驻): 让第一个倒下的队友以30%体力复活一次',
    breath: (cd: number) => `火焰: 每攻击${cd}次，灼烧全体敌人 (60%)`,
    thorns: () => '尖刺岩（常驻）: 受到攻击时，把所受伤害的30%反弹给攻击者',
    scream: (cd: number) => `尖啸: 每攻击${cd}次，使一名敌人晕眩1秒`,
    lifesteal: () => '吸血（常驻）: 回复造成伤害的20%',
    execute: (cd: number) => `处决: 每攻击${cd}次，对体力最低的敌人造成1.3倍伤害`,
    double_shot: (cd: number) => `连射: 每攻击${cd}次，射击两次 (各60%)`,
    heal: (cd: number) => `治愈: 每攻击${cd}次，为伤势最重的队友恢复25%体力`,
    dark_wave: (cd: number) => `暗黑波动: 每攻击${cd}次，攻击全体敌人 (80%)`,
    frenzy: (cd: number) => `狂乱: 每攻击${cd}次，抓两次 (各60%)`,
    gaze: (cd: number) => `深渊凝视: 每攻击${cd}次，攻击全体敌人 (50%)`,
  } as Record<string, (cd: number) => string>,
  tut: {
    raidSortie: '白天化身勇者去抢别人的城堡赚金币。请点出征！',
    raidPick: '选择要抢的城堡。战力比我们越低越容易。先从这个见习公会开始！',
    night: '夜幕降临！勇者们正攻向我们的城堡。魔王大人，请守住城堡！',
    raidUlt: '气攒满后，必杀技会自动发动。请欣赏！',
    raidResult: '金币到手了！',
    placeFloor: '现在也得守住我们的城堡。请点1层。',
    placeSlot: '在空位上安排手下。',
    upgradeTab: '用金币让手下变强！',
    upgradeOne: '强化一次看看吧。',
    matchSortie: '这次是真正别人的城堡。出征！',
    end: '接下来跟着下面的「下一步」走吧，魔王大人！',
  },
  cutscene: {
    skip: '跳过',
    lines: [
      '小恶魔：“魔王大人，城堡的维修费已经拖欠三个月了。”',
      '小恶魔：“隔壁的魔王城金币多得溢出来…可惜勇者们天天去抢。”',
      '魔王：“…那我也去当勇者就行了。”',
      '魔王：“白天当勇者去抢别人的城堡，”',
      '魔王：“晚上当魔王守住自己的城堡。”',
    ],
    title: '白天是勇者，晚上是魔王',
  },
  nick: {
    title: '魔王的名字',
    hint: '2〜8个字，韩文・英文・数字',
    placeholder: '名字',
    submit: '就决定是这个',
  },
  settings: {
    title: '设置',
    bgm: '背景音乐',
    sfx: '音效',
    on: '开启',
    off: '关闭',
    nickname: '昵称',
    renameLeft: (n: number) => `免费修改剩余${n}次`,
    rename: '修改',
    reset: '重置数据',
    resetWarn: '所有数据都会回到最初：城堡、等级、觉醒星、金币、魂石、外观、VIP、已购买的商品（3倍速、高级、赛季通行证等）、记录与最高波次。已购买的商品与货币也会消失，无法恢复或退款。只保留昵称，并重新开始教学。',
    resetType: '请输入“重置”以确认',
    resetWord: '重置',
    resetGo: '重置',
    resetDone: '已重置',
    lordLook: '魔王外观',
    lookOwned: (n: number, pct: number) => `拥有外观 ${n} 个 · 魔王属性 +${pct}%（无需穿戴）`,
    looks: { base: '基本', dragon: '黑龙', lava: '熔岩魔王', demon: '紫翼恶魔', summon1: '堕落大恶魔', hydra: '三首海德拉', spend1: '晶冠海妖', lich: '骨龙巫妖王', abyss: '独眼深渊君主', emperor: '深渊皇帝' } as Record<string, string>,
    wornFx: '穿戴效果',
    lookFx: { dragon: '暗黑波动每攻击3次', lava: '反弹受到伤害的30%', demon: '吸取造成伤害的20%', summon1: '对最弱敌人造成2倍伤害', hydra: '普通攻击同时咬3人', spend1: '所有楼层怪物+10%', lich: '一次以50%生命复活', abyss: '暗黑波动使敌人眩晕1秒', emperor: '暗黑波动伤害2倍' } as Record<string, string>,
  },
  pass: {
    rank: '排名',
    track: '通行证',
    howTier: (n: number) => `每${n}荣誉升1阶`,
    tier: (n: number) => `第${n}阶`,
    done: '完成',
    prev: '上一页',
    next: '下一页',
    dragon: '黑龙',
    passOnly: '通行证',
    claimAll: '全部领取',
    only: '通行证专属',
    dragonKeep: '第10阶 · 永久拥有',
    ownBonus: '只要拥有，魔王属性 ',
    buy: '购买通行证',
    value: (pct: number) => `比购买魂石多 +${pct}%`,
    got: (gold: number, soul: number, skin: boolean) =>
      `已领取！ ${[gold ? `金币 ${F(gold)}` : '', soul ? `魂石 ${soul}` : '', skin ? '黑龙外观' : ''].filter(Boolean).join(' · ')}`,
  },
  stuck: {
    title: (n: number) => `卡在第${n}波`,
    sub: '这样可以变强',
    advice: (need: string, mine: string) => `推荐战力 ${need} · 当前 ${mine}`,
    fill: (name: string) => `把${name}放到空格`,
    monster: (name: string) => `强化${name}`,
    castle: '强化城堡 — 魔王等级大幅提升',
    lord: '觉醒魔王 — 用魂石立刻变强',
    hero: (name: string) => `强化${name} — 入侵防御 +1%`,
    summon: '召唤 — 装备外观能力 +10%',
    shop: '获取魂石 — 用于觉醒和召唤',
    go: '前往',
  },
  away: {
    title: '离开的这段时间',
    gold: (g: number) => `累积金币 +${F(g)}`,
    later: '稍后',
  },
  siege: {
    farm: (n: number) => `第${n}波 重复中`,
    challenge: (n: number) => `挑战第${n}波`,
    challengeReady: '挑战中！',
    advice: (p: string) => `推荐 ${p}`,
    breachedFarm: '被突破！重复上一波',
    stage: (n: number) => `第${n}波`,
    next: (n: number, ms: number) => `第${n}波 · ${Math.floor(ms / 60_000)}:${String(Math.floor(ms / 1000) % 60).padStart(2, '0')}`,
    breached: '王座失守！波次下降',
    call: '立即召唤',
    rankTab: '波次',
    best: (n: number) => `最高 ${n}`,
    myBest: (n: number) => `我的最高 第${n}波`,
    milestoneHint: '每刷新一次最高波次得魂石10，每10波再加',
    seasonBest: (n: number) => `本赛季 第${n}波`,
    seasonReward: (a: number, b: number, c: number) => `赛季结束魂石 第1名 ${a} · 第2名 ${b} · 第3名 ${c}`,
    noRank: '还没有记录',
    rankFailed: '无法加载排名',
    milestone: (soul: number) => `波次首次突破！魂石 +${soul}`,
    power: '战力',
    heroHint: '攻略时出战的我方队伍。越强越容易抢下别人的城堡',
    heroBonus: (p: number) => `当前 掠夺金币 +${p}% · 入侵防守 +${p}%`,
    heroNext: (p: number, next: number) => `强化后 掠夺金币・入侵防守 +${p}% → +${next}%`,
  },
  ads: {
    watch: (label: string) => `${label} (广告)`,
    instant: (label: string) => `${label} (立即)`,
    dismissed: '看完广告才能领取',
    failed: '现在无法观看广告，请稍后再试',
    left: (n: number) => `今天剩${n}次`,
    tomorrow: '明天再来',
    supply: '每日补给',
    supplyDesc: (gold: number, soul: number) => `金币 ${F(gold)} + 魂石 ${soul}`,
    receive: '领取',
    revenge: '复仇 +1',
    revive: '复活',
    plain: (g: number) => `直接领取 +${F(g)}`,
    double: (mult: number, g: number) => `${mult}倍领取 +${F(g)}`,
    got: '已领取！',
  },
  errors: {
    AD_PLACEMENT: '请再试一次',
    AD_LIMIT: '今天已经全部领完了',
    AD_NOT_NOW: '现在无法领取',
    AD_NOT_VERIFIED: '无法确认广告，请再试一次',
    AD_USED: '这个广告奖励已经领过了',
    NICK_LENGTH: '名字请用2〜8个字',
    NICK_CHARS: '只能使用韩文、英文与数字',
    NICK_JAMO: '不能只用ㄱ、ㅏ这类单独字母，请输入完整的韩文字',
    NICK_BANNED: '这个名字不能使用',
    NICK_TAKEN: '这个名字已经有人用了',
    NICK_NO_CHANGES: '免费修改已经用过了',
    SKIN_NOT_OWNED: '没有这个外观',
    SIEGE_TOO_SOON: '还不能召唤下一波',
    NO_SPEED3: '3倍速是商店商品',
    PASS_NOTHING: '没有可领取的奖励',
    RESET_CONFIRM: '请正确输入“重置”',
    RESET_IN_RAID: '攻略中无法重置',
    ONBOARDING_ORDER: '请再试一次',
    NO_REVIVE_CREDIT: '没有复活道具',
    NO_REVENGE_CREDIT: '今天3次免费复仇已用完，需要复仇券',
    NO_SORTIE: '没有出征券。每10分钟恢复1张，也可用金币购买',
    NO_SOUL: '魂石不足',
    MAX_STARS: '已经完全觉醒',
    AWAKEN_FIRST: '已达50级，觉醒后才能继续提升',
    LEVEL_FIRST: '达到50级才能觉醒',
    generic: '出了点问题，请稍后再试。',
  } as Record<string, string>,
  serverMsg: {
    '골드가 부족하다': '金币不足',
    '영혼석이 부족하다': '魂石不足',
    '최대 레벨이다': '已经是最高等级',
    '성이 최대 레벨이다': '城堡已是最高等级',
    '이미 공략 중이다': '已经在攻略中',
    '공략 중에는 편성을 바꿀 수 없다': '攻略中无法修改编组',
    '복수 기한(24시간)이 지났다': '已超过复仇期限 (24小时)',
    '복수할 수 없는 기록이다': '这条记录无法复仇',
    '부활은 판당 1회다': '每场攻略只能复活1次',
    '이미 보유한 몬스터다': '已经拥有这只怪物',
    '다시 시도해줘': '请再试一次',
  } as Record<string, string>,
  units: {
    slime: '史莱姆', skeleton: '骷髅兵', imp: '小恶魔', spider: '蜘蛛', necro: '死灵法师', dragon: '幼龙', golem: '岩石魔像', banshee: '女妖', vampire: '吸血鬼', deathknight: '死亡骑士', werewolf: '狼人', mushroom: '瘟疫蘑菇', eye: '深渊之眼',
    knight: '骑士', archer: '弓箭手', priest: '圣职者', lord: '魔王',
  } as Record<string, string>,
  fx: { taunt: '嘲讽', web: '蛛网', stun: '眩晕', down: '倒下', raise: '化为亡灵复活', cleared: '突破楼层' } as Record<string, string>,
  names: {
    guild: '入侵者公会',
    guildApprentice: '入侵者公会 见习',
    guildRookie: '入侵者公会 新人',
    guildTier: (n: number) => `入侵者公会 ${n}段`,
    ghost: (n: number) => `暗影魔王 ${n}`,
    lordTag: (tag: string) => `魔王 #${tag}`,
  },
  load: {
    top: '白天是勇者，',
    main: '晚上是魔王',
    connect: '正在连接服务器…',
    home: '正在加载城堡…',
    assets: '正在打开城门…',
    tips: [
      '提示: 离开时勇者也会继续入侵',
      '提示: 复仇可得2倍荣誉',
      '提示: 强化勇者会增加掠夺金币',
      '提示: 每刷新一次最高波次就能获得魂石',
    ],
  },
  vip: {
    level: (n: number) => `VIP ${n}`,
    none: '非VIP',
    toNext: (vx: number, n: number) => `距离 VIP ${n} 还差 ${vx.toLocaleString()} VX`,
    max: '最高等级',
    nextTitle: '下一等级福利',
    idle: (p: number) => `挂机收益 +${p}%`,
    away: (m: number) => `离开时波次金币 ×${m}`,
    cap: (h: number) => `挂机上限 ${h}小时`,
    pack: (p: number) => `金币礼包 +${p}%`,
    idleAd: (n: number) => `广告1.5倍 每天${n}次`,
    revenge: (n: number) => `免费复仇 每天${n}次`,
    nickname: '昵称免费修改 +1',
    skin: (name: string) => `专属外观: ${name}`,
    aura: '红宝石光环',
    skins: { lava: '熔岩魔王', demon: '紫翼恶魔' } as Record<string, string>,
  },
  awaken: {
    upTab: '强化',
    tab: '觉醒',
    hint: '每颗星让全部能力×1.1。消耗魂石，重置后仍保留。',
    btn: (soul: number) => `觉醒（魂石 ${F(soul)}）`,
    max: '已完全觉醒',
    lordHint: '与城堡等级分开，每颗星能力×1.1',
    mult: (now: string, next: string | null) => (next ? `能力 ×${now} → ×${next}` : `能力 ×${now}`),
    buySoul: '购买魂石',
  },
  news: {
    vip10: (name: string) => `${name} 达到 VIP 10！`,
    star20: (name: string) => `${name}觉醒到五颗金星！`,
    champion: (name: string) => `${name} 拿下上赛季全服第1名，成为「霸王」！`,
  } as Record<string, (name: string) => string>,
  summon: {
    open: '召唤',
    pity: (n: number) => `距离英雄以上还有${n}次`,
    legendPity: (n: number) => `距离传说还有${n}次`,
    rates: '概率',
    one: '1次',
    ten: '10+1次',
    result: '召唤结果',
    ok: '确定',
    skipAnim: '跳过演出',
    skip: '全部显示',
    fresh: 'NEW',
    look: (name: string) => `外观: ${name}`,
    baseLook: '基本',
    wearWhere: '获得的外观在强化画面的怪物栏穿上',
    ratesTitle: '召唤概率',
    grades: { common: '普通', rare: '稀有', epic: '英雄', legend: '传说' },
    rewardOf: { common: '魂石 10', rare: '魂石 30', epic: '12种怪物装备外观之一', legend: '2种召唤限定魔王外观之一' },
    tenNote: '10+1次必得一个英雄以上。',
    pityNote: (n: number) => `连续没有英雄以上时，第${n}次召唤必得英雄以上；抽到后重新计算。`,
    legendPityNote: (n: number) => `连续没有传说时，第${n}次召唤必得传说；抽到后重新计算。`,
    dupNote: (epic: number, legend: number) => `抽到已有的外观会换成魂石(英雄${epic}、传说${F(legend)})。`,
    detail: { tap: '点击查看详情', gear: (m: string, p: number) => `${m}专属装备外观 · 穿戴后能力 +${p}%`, legend: (p: number) => `魔王外观 · 拥有即魔王能力 +${p}%`, dup: (n: number) => `已拥有，转换为魂石${n}`, soul: (n: number) => `获得魂石${n}个`, wear: '可在强化界面穿戴', wearLord: '可在强化界面的魔王一栏穿戴' },
    gear: {
      'slime:crown': '史莱姆王', 'slime:helm': '骑士史莱姆', 'skeleton:royal': '骷髅王', 'skeleton:dread': '恐惧之铠',
      'imp:king': '小恶魔王', 'imp:warlock': '黑巫师小恶魔', 'necro:lich': '巫妖王', 'necro:bone': '骨甲',
      'spider:iron': '钢铁蜘蛛', 'spider:crown': '蜘蛛女王', 'dragon:knight': '骑士龙', 'dragon:royal': '王室之龙',
    } as Record<string, string>,
  },
  lang: { title: '语言', pick: '请选择语言', go: '开始' },
};
